// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as ImageSize from "image-size";
import * as UnistUtilVisit from "unist-util-visit";

function toJsx(tree) {
  return UnistUtilVisit.visit(tree, (function (node) {
                if (node.type === "paragraph") {
                  return Curry._1(node.children.some, (function (n) {
                                return n.type === "image";
                              }));
                } else {
                  return false;
                }
              }), (function (node, param, param$1) {
                var imageNode = Curry._1(node.children.find, (function (n) {
                        return n.type === "image";
                      }));
                if (!Fs.existsSync(process.cwd() + "/public" + imageNode.url)) {
                  return ;
                }
                var dimensions = ImageSize.sizeof(process.cwd() + "/public" + imageNode.url);
                imageNode.type = "mdxJsxFlowElement";
                imageNode.name = "Image";
                imageNode.attributes = [
                  {
                    type_: "mdxJsxAttribute",
                    name: "alt",
                    value: imageNode.alt
                  },
                  {
                    type_: "mdxJsxAttribute",
                    name: "src",
                    value: imageNode.url
                  },
                  {
                    type_: "mdxJsxAttribute",
                    name: "width",
                    value: String(dimensions.width)
                  },
                  {
                    type_: "mdxJsxAttribute",
                    name: "height",
                    value: String(dimensions.height)
                  }
                ];
                node.type = "div";
                node.children = [imageNode];
                
              }));
}

export {
  toJsx ,
  
}
/* fs Not a pure module */
