// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_format from "rescript/lib/es6/caml_format.js";
import GrayMatter from "gray-matter";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";
import * as NodeJS$RescriptMonorepo from "../bindings/NodeJS.mjs";

var root = process.cwd();

function join(prim) {
  return Caml_splice_call.spliceApply(Path.join, [prim]);
}

var readFileSync = NodeJS$RescriptMonorepo.Fs.readFileSync;

function postFilePaths($$location) {
  return Belt_Array.keep(NodeJS$RescriptMonorepo.Fs.readdirSync(undefined, undefined, Path.join(root, "data", $$location)), (function (path) {
                return /\.mdx?$/.test(path);
              }));
}

function prependPathSegment($$location, pathSegment) {
  return Path.join($$location, pathSegment);
}

function readdirPreserveRelativePath($$location) {
  return Belt_Array.map(NodeJS$RescriptMonorepo.Fs.readdirSync(undefined, undefined, $$location), (function (pathSegment) {
                return Path.join($$location, pathSegment);
              }));
}

function readdirRecursive($$location) {
  return Belt_Array.reduce(readdirPreserveRelativePath($$location), [], (function (result, currentValue) {
                if (NodeJS$RescriptMonorepo.Fs.statSync(undefined, undefined, currentValue).isDirectory()) {
                  return Belt_Array.concat(result, readdirRecursive(currentValue));
                } else {
                  return Belt_Array.concat([currentValue], result);
                }
              }));
}

function removeMdxExtension(slug) {
  return slug.replace(/\.(mdx|md)?$/, "");
}

function toFileTypeValue(extension) {
  if (extension === "mdx") {
    return "mdx";
  } else {
    return "md";
  }
}

function getFileBySlug(rootOpt, slug) {
  var root$1 = rootOpt !== undefined ? rootOpt : root;
  var mdxPath = Path.join(root$1, "data", slug.join("/") + ".mdx");
  var mdPath = Path.join(root$1, "data", slug.join("/") + ".mdx");
  if (Fs.existsSync(mdxPath)) {
    return NodeJS$RescriptMonorepo.Fs.readFileSync(undefined, undefined, mdxPath);
  } else {
    return NodeJS$RescriptMonorepo.Fs.readFileSync(undefined, undefined, mdPath);
  }
}

function removeRoot(rootOpt, string) {
  var root$1 = rootOpt !== undefined ? rootOpt : root;
  return string.replace(Path.join(root$1, "/data"), "");
}

function getFiles(rootOpt, $$location) {
  var root$1 = rootOpt !== undefined ? rootOpt : root;
  var prefixPaths = Path.join(root$1, "data", $$location);
  var files = readdirRecursive(prefixPaths);
  return files.map(function (file) {
              return removeMdxExtension(removeRoot(undefined, file));
            });
}

function sortDesc(a, b) {
  var resultA = a.split("-");
  var resultB = b.split("-");
  var yearA = Caml_format.caml_int_of_string(Caml_array.get(resultA, 0));
  var monthA = Caml_format.caml_int_of_string(Caml_array.get(resultA, 1));
  var dayA = Caml_format.caml_int_of_string(Caml_array.get(resultA, 2));
  var yearB = Caml_format.caml_int_of_string(Caml_array.get(resultB, 0));
  var monthB = Caml_format.caml_int_of_string(Caml_array.get(resultB, 1));
  var dayB = Caml_format.caml_int_of_string(Caml_array.get(resultB, 2));
  if (yearA > yearB) {
    return -1;
  } else if (yearA === yearB) {
    if (monthA > monthB) {
      return -1;
    } else if (monthA === monthB) {
      if (dayA > dayB) {
        return -1;
      } else if (dayA === dayB) {
        return 0;
      } else {
        return 1;
      }
    } else {
      return 1;
    }
  } else {
    return 1;
  }
}

function getBlogPostsFromLatest(cwdOpt, pathOpt, param) {
  var cwd = cwdOpt !== undefined ? cwdOpt : root;
  var path = pathOpt !== undefined ? pathOpt : [
      "data",
      "blog"
    ];
  var buildPath = Caml_splice_call.spliceApply(Path.join, [[cwd].concat(path)]);
  var files = readdirRecursive(buildPath);
  var frontmatterArray = files.reduce((function (acc, file) {
          var fileName = file.replace(/\\/g, "/");
          var source = readFileSync(undefined, undefined, fileName);
          var slug = removeMdxExtension(removeRoot(undefined, fileName));
          var match = GrayMatter(source);
          var data = match.data;
          var string = data.lastmod;
          var lastmod = (string == null) ? "" : string;
          var bool = data.draft;
          var isDraft = (bool == null) ? true : bool;
          var string$1 = data.summary;
          var summary = (string$1 == null) ? "" : string$1;
          var array = data.images;
          var images = (array == null) ? [] : array;
          var withSlug_title = data.title;
          var withSlug_date = data.date;
          var withSlug_tags = data.tags;
          var bool$1 = data.draft;
          if (!(bool$1 == null) && !bool$1) {
            return acc.concat([{
                          title: withSlug_title,
                          date: withSlug_date,
                          tags: withSlug_tags,
                          lastmod: lastmod,
                          draft: bool$1,
                          summary: summary,
                          images: images,
                          slug: slug
                        }]);
          } else {
            return acc;
          }
        }), []);
  return frontmatterArray.sort(function (a, b) {
              return sortDesc(a.date, b.date);
            });
}

function returnSiteMetadata(pathOpt, param) {
  var path = pathOpt !== undefined ? pathOpt : [
      "data",
      "siteMetadata.json"
    ];
  var metadataPath = Caml_splice_call.spliceApply(Path.join, [[root].concat(path)]);
  return JSON.parse(NodeJS$RescriptMonorepo.Fs.readFileSync(undefined, undefined, metadataPath));
}

function kebabCase(str) {
  var matches = str.match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g);
  if (matches !== null) {
    return matches.map(function (x) {
                  return x.toLocaleLowerCase();
                }).join("-");
  } else {
    return "";
  }
}

var Params = {};

function getFormattedFiles($$location) {
  return Belt_Array.map(getFiles(undefined, $$location), (function (slug) {
                return slug.replace(/^\/blog\//, "");
              }));
}

export {
  root ,
  join ,
  readFileSync ,
  postFilePaths ,
  prependPathSegment ,
  readdirPreserveRelativePath ,
  readdirRecursive ,
  removeMdxExtension ,
  toFileTypeValue ,
  getFileBySlug ,
  removeRoot ,
  getFiles ,
  sortDesc ,
  getBlogPostsFromLatest ,
  returnSiteMetadata ,
  kebabCase ,
  Params ,
  getFormattedFiles ,
  
}
/* root Not a pure module */
