// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";
import * as Nav$RescriptMonorepo from "../Nav.mjs";

var navStyles = "bg-gray-700 md:flex md:items-center md:justify-between text-white py-2 px-8 md:px-16  border-red-500 border-b-2";

var Styles = {
  navStyles: navStyles
};

function NavAcme(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement(Nav$RescriptMonorepo.make, {
              children: children,
              className: CssJs.merge([
                    navStyles,
                    className
                  ])
            });
}

var make = NavAcme;

export {
  Styles ,
  make ,
  
}
/* CssJs Not a pure module */
