open CssJs

// NOTE: Background Color - Utilities for controlling an element's background color.
let bgTransparent = [backgroundColor(#transparent)]
let bgCurrent = [backgroundColor(#currentColor)]
let bgBlack = opacity => [backgroundColor(Theme.Colors.black(opacity))]
let bgWhite = opacity => [backgroundColor(Theme.Colors.white(opacity))]

let bgGray50 = opacity => [backgroundColor(Theme.Colors.gray50(opacity))]
let bgGray100 = opacity => [backgroundColor(Theme.Colors.gray100(opacity))]
let bgGray200 = opacity => [backgroundColor(Theme.Colors.gray200(opacity))]
let bgGray300 = opacity => [backgroundColor(Theme.Colors.gray300(opacity))]
let bgGray400 = opacity => [backgroundColor(Theme.Colors.gray400(opacity))]
let bgGray500 = opacity => [backgroundColor(Theme.Colors.gray500(opacity))]
let bgGray600 = opacity => [backgroundColor(Theme.Colors.gray600(opacity))]
let bgGray700 = opacity => [backgroundColor(Theme.Colors.gray700(opacity))]
let bgGray800 = opacity => [backgroundColor(Theme.Colors.gray800(opacity))]
let bgGray900 = opacity => [backgroundColor(Theme.Colors.gray900(opacity))]

let bgBlueGray50 = opacity => [backgroundColor(Theme.Colors.blueGray50(opacity))]
let bgBlueGray100 = opacity => [backgroundColor(Theme.Colors.blueGray100(opacity))]
let bgBlueGray200 = opacity => [backgroundColor(Theme.Colors.blueGray200(opacity))]
let bgBlueGray300 = opacity => [backgroundColor(Theme.Colors.blueGray300(opacity))]
let bgBlueGray400 = opacity => [backgroundColor(Theme.Colors.blueGray400(opacity))]
let bgBlueGray500 = opacity => [backgroundColor(Theme.Colors.blueGray500(opacity))]
let bgBlueGray600 = opacity => [backgroundColor(Theme.Colors.blueGray600(opacity))]
let bgBlueGray700 = opacity => [backgroundColor(Theme.Colors.blueGray700(opacity))]
let bgBlueGray800 = opacity => [backgroundColor(Theme.Colors.blueGray800(opacity))]
let bgBlueGray900 = opacity => [backgroundColor(Theme.Colors.blueGray900(opacity))]

let bgCoolGray50 = opacity => [backgroundColor(Theme.Colors.coolGray50(opacity))]
let bgCoolGray100 = opacity => [backgroundColor(Theme.Colors.coolGray100(opacity))]
let bgCoolGray200 = opacity => [backgroundColor(Theme.Colors.coolGray200(opacity))]
let bgCoolGray300 = opacity => [backgroundColor(Theme.Colors.coolGray300(opacity))]
let bgCoolGray400 = opacity => [backgroundColor(Theme.Colors.coolGray400(opacity))]
let bgCoolGray500 = opacity => [backgroundColor(Theme.Colors.coolGray500(opacity))]
let bgCoolGray600 = opacity => [backgroundColor(Theme.Colors.coolGray600(opacity))]
let bgCoolGray700 = opacity => [backgroundColor(Theme.Colors.coolGray700(opacity))]
let bgCoolGray800 = opacity => [backgroundColor(Theme.Colors.coolGray800(opacity))]
let bgCoolGray900 = opacity => [backgroundColor(Theme.Colors.coolGray900(opacity))]

let bgTrueGray50 = opacity => [backgroundColor(Theme.Colors.trueGray50(opacity))]
let bgTrueGray100 = opacity => [backgroundColor(Theme.Colors.trueGray100(opacity))]
let bgTrueGray200 = opacity => [backgroundColor(Theme.Colors.trueGray200(opacity))]
let bgTrueGray300 = opacity => [backgroundColor(Theme.Colors.trueGray300(opacity))]
let bgTrueGray400 = opacity => [backgroundColor(Theme.Colors.trueGray400(opacity))]
let bgTrueGray500 = opacity => [backgroundColor(Theme.Colors.trueGray500(opacity))]
let bgTrueGray600 = opacity => [backgroundColor(Theme.Colors.trueGray600(opacity))]
let bgTrueGray700 = opacity => [backgroundColor(Theme.Colors.trueGray700(opacity))]
let bgTrueGray800 = opacity => [backgroundColor(Theme.Colors.trueGray800(opacity))]
let bgTrueGray900 = opacity => [backgroundColor(Theme.Colors.trueGray900(opacity))]

let bgWarmGray50 = opacity => [backgroundColor(Theme.Colors.warmGray50(opacity))]
let bgWarmGray100 = opacity => [backgroundColor(Theme.Colors.warmGray100(opacity))]
let bgWarmGray200 = opacity => [backgroundColor(Theme.Colors.warmGray200(opacity))]
let bgWarmGray300 = opacity => [backgroundColor(Theme.Colors.warmGray300(opacity))]
let bgWarmGray400 = opacity => [backgroundColor(Theme.Colors.warmGray400(opacity))]
let bgWarmGray500 = opacity => [backgroundColor(Theme.Colors.warmGray500(opacity))]
let bgWarmGray600 = opacity => [backgroundColor(Theme.Colors.warmGray600(opacity))]
let bgWarmGray700 = opacity => [backgroundColor(Theme.Colors.warmGray700(opacity))]
let bgWarmGray800 = opacity => [backgroundColor(Theme.Colors.warmGray800(opacity))]
let bgWarmGray900 = opacity => [backgroundColor(Theme.Colors.warmGray900(opacity))]

let bgRed50 = opacity => [backgroundColor(Theme.Colors.red50(opacity))]
let bgRed100 = opacity => [backgroundColor(Theme.Colors.red100(opacity))]
let bgRed200 = opacity => [backgroundColor(Theme.Colors.red200(opacity))]
let bgRed300 = opacity => [backgroundColor(Theme.Colors.red300(opacity))]
let bgRed400 = opacity => [backgroundColor(Theme.Colors.red400(opacity))]
let bgRed500 = opacity => [backgroundColor(Theme.Colors.red500(opacity))]
let bgRed600 = opacity => [backgroundColor(Theme.Colors.red600(opacity))]
let bgRed700 = opacity => [backgroundColor(Theme.Colors.red700(opacity))]
let bgRed800 = opacity => [backgroundColor(Theme.Colors.red800(opacity))]
let bgRed900 = opacity => [backgroundColor(Theme.Colors.red900(opacity))]

let bgOrange50 = opacity => [backgroundColor(Theme.Colors.orange50(opacity))]
let bgOrange100 = opacity => [backgroundColor(Theme.Colors.orange100(opacity))]
let bgOrange200 = opacity => [backgroundColor(Theme.Colors.orange200(opacity))]
let bgOrange300 = opacity => [backgroundColor(Theme.Colors.orange300(opacity))]
let bgOrange400 = opacity => [backgroundColor(Theme.Colors.orange400(opacity))]
let bgOrange500 = opacity => [backgroundColor(Theme.Colors.orange500(opacity))]
let bgOrange600 = opacity => [backgroundColor(Theme.Colors.orange600(opacity))]
let bgOrange700 = opacity => [backgroundColor(Theme.Colors.orange700(opacity))]
let bgOrange800 = opacity => [backgroundColor(Theme.Colors.orange800(opacity))]
let bgOrange900 = opacity => [backgroundColor(Theme.Colors.orange900(opacity))]

let bgAmber50 = opacity => [backgroundColor(Theme.Colors.amber50(opacity))]
let bgAmber100 = opacity => [backgroundColor(Theme.Colors.amber100(opacity))]
let bgAmber200 = opacity => [backgroundColor(Theme.Colors.amber200(opacity))]
let bgAmber300 = opacity => [backgroundColor(Theme.Colors.amber300(opacity))]
let bgAmber400 = opacity => [backgroundColor(Theme.Colors.amber400(opacity))]
let bgAmber500 = opacity => [backgroundColor(Theme.Colors.amber500(opacity))]
let bgAmber600 = opacity => [backgroundColor(Theme.Colors.amber600(opacity))]
let bgAmber700 = opacity => [backgroundColor(Theme.Colors.amber700(opacity))]
let bgAmber800 = opacity => [backgroundColor(Theme.Colors.amber800(opacity))]
let bgAmber900 = opacity => [backgroundColor(Theme.Colors.amber900(opacity))]

let bgYellow50 = opacity => [backgroundColor(Theme.Colors.yellow50(opacity))]
let bgYellow100 = opacity => [backgroundColor(Theme.Colors.yellow100(opacity))]
let bgYellow200 = opacity => [backgroundColor(Theme.Colors.yellow200(opacity))]
let bgYellow300 = opacity => [backgroundColor(Theme.Colors.yellow300(opacity))]
let bgYellow400 = opacity => [backgroundColor(Theme.Colors.yellow400(opacity))]
let bgYellow500 = opacity => [backgroundColor(Theme.Colors.yellow500(opacity))]
let bgYellow600 = opacity => [backgroundColor(Theme.Colors.yellow600(opacity))]
let bgYellow700 = opacity => [backgroundColor(Theme.Colors.yellow700(opacity))]
let bgYellow800 = opacity => [backgroundColor(Theme.Colors.yellow800(opacity))]
let bgYellow900 = opacity => [backgroundColor(Theme.Colors.yellow900(opacity))]

let bgLime50 = opacity => [backgroundColor(Theme.Colors.lime50(opacity))]
let bgLime100 = opacity => [backgroundColor(Theme.Colors.lime100(opacity))]
let bgLime200 = opacity => [backgroundColor(Theme.Colors.lime200(opacity))]
let bgLime300 = opacity => [backgroundColor(Theme.Colors.lime300(opacity))]
let bgLime400 = opacity => [backgroundColor(Theme.Colors.lime400(opacity))]
let bgLime500 = opacity => [backgroundColor(Theme.Colors.lime500(opacity))]
let bgLime600 = opacity => [backgroundColor(Theme.Colors.lime600(opacity))]
let bgLime700 = opacity => [backgroundColor(Theme.Colors.lime700(opacity))]
let bgLime800 = opacity => [backgroundColor(Theme.Colors.lime800(opacity))]
let bgLime900 = opacity => [backgroundColor(Theme.Colors.lime900(opacity))]

let bgGreen50 = opacity => [backgroundColor(Theme.Colors.green50(opacity))]
let bgGreen100 = opacity => [backgroundColor(Theme.Colors.green100(opacity))]
let bgGreen200 = opacity => [backgroundColor(Theme.Colors.green200(opacity))]
let bgGreen300 = opacity => [backgroundColor(Theme.Colors.green300(opacity))]
let bgGreen400 = opacity => [backgroundColor(Theme.Colors.green400(opacity))]
let bgGreen500 = opacity => [backgroundColor(Theme.Colors.green500(opacity))]
let bgGreen600 = opacity => [backgroundColor(Theme.Colors.green600(opacity))]
let bgGreen700 = opacity => [backgroundColor(Theme.Colors.green700(opacity))]
let bgGreen800 = opacity => [backgroundColor(Theme.Colors.green800(opacity))]
let bgGreen900 = opacity => [backgroundColor(Theme.Colors.green900(opacity))]

let bgEmerald50 = opacity => [backgroundColor(Theme.Colors.emerald50(opacity))]
let bgEmerald100 = opacity => [backgroundColor(Theme.Colors.emerald100(opacity))]
let bgEmerald200 = opacity => [backgroundColor(Theme.Colors.emerald200(opacity))]
let bgEmerald300 = opacity => [backgroundColor(Theme.Colors.emerald300(opacity))]
let bgEmerald400 = opacity => [backgroundColor(Theme.Colors.emerald400(opacity))]
let bgEmerald500 = opacity => [backgroundColor(Theme.Colors.emerald500(opacity))]
let bgEmerald600 = opacity => [backgroundColor(Theme.Colors.emerald600(opacity))]
let bgEmerald700 = opacity => [backgroundColor(Theme.Colors.emerald700(opacity))]
let bgEmerald800 = opacity => [backgroundColor(Theme.Colors.emerald800(opacity))]
let bgEmerald900 = opacity => [backgroundColor(Theme.Colors.emerald900(opacity))]

let bgTeal50 = opacity => [backgroundColor(Theme.Colors.teal50(opacity))]
let bgTeal100 = opacity => [backgroundColor(Theme.Colors.teal100(opacity))]
let bgTeal200 = opacity => [backgroundColor(Theme.Colors.teal200(opacity))]
let bgTeal300 = opacity => [backgroundColor(Theme.Colors.teal300(opacity))]
let bgTeal400 = opacity => [backgroundColor(Theme.Colors.teal400(opacity))]
let bgTeal500 = opacity => [backgroundColor(Theme.Colors.teal500(opacity))]
let bgTeal600 = opacity => [backgroundColor(Theme.Colors.teal600(opacity))]
let bgTeal700 = opacity => [backgroundColor(Theme.Colors.teal700(opacity))]
let bgTeal800 = opacity => [backgroundColor(Theme.Colors.teal800(opacity))]
let bgTeal900 = opacity => [backgroundColor(Theme.Colors.teal900(opacity))]

let bgCyan50 = opacity => [backgroundColor(Theme.Colors.cyan50(opacity))]
let bgCyan100 = opacity => [backgroundColor(Theme.Colors.cyan100(opacity))]
let bgCyan200 = opacity => [backgroundColor(Theme.Colors.cyan200(opacity))]
let bgCyan300 = opacity => [backgroundColor(Theme.Colors.cyan300(opacity))]
let bgCyan400 = opacity => [backgroundColor(Theme.Colors.cyan400(opacity))]
let bgCyan500 = opacity => [backgroundColor(Theme.Colors.cyan500(opacity))]
let bgCyan600 = opacity => [backgroundColor(Theme.Colors.cyan600(opacity))]
let bgCyan700 = opacity => [backgroundColor(Theme.Colors.cyan700(opacity))]
let bgCyan800 = opacity => [backgroundColor(Theme.Colors.cyan800(opacity))]
let bgCyan900 = opacity => [backgroundColor(Theme.Colors.cyan900(opacity))]

let bgLightBlue50 = opacity => [backgroundColor(Theme.Colors.lightBlue50(opacity))]
let bgLightBlue100 = opacity => [backgroundColor(Theme.Colors.lightBlue100(opacity))]
let bgLightBlue200 = opacity => [backgroundColor(Theme.Colors.lightBlue200(opacity))]
let bgLightBlue300 = opacity => [backgroundColor(Theme.Colors.lightBlue300(opacity))]
let bgLightBlue400 = opacity => [backgroundColor(Theme.Colors.lightBlue400(opacity))]
let bgLightBlue500 = opacity => [backgroundColor(Theme.Colors.lightBlue500(opacity))]
let bgLightBlue600 = opacity => [backgroundColor(Theme.Colors.lightBlue600(opacity))]
let bgLightBlue700 = opacity => [backgroundColor(Theme.Colors.lightBlue700(opacity))]
let bgLightBlue800 = opacity => [backgroundColor(Theme.Colors.lightBlue800(opacity))]
let bgLightBlue900 = opacity => [backgroundColor(Theme.Colors.lightBlue900(opacity))]

let bgBlue50 = opacity => [backgroundColor(Theme.Colors.blue50(opacity))]
let bgBlue100 = opacity => [backgroundColor(Theme.Colors.blue100(opacity))]
let bgBlue200 = opacity => [backgroundColor(Theme.Colors.blue200(opacity))]
let bgBlue300 = opacity => [backgroundColor(Theme.Colors.blue300(opacity))]
let bgBlue400 = opacity => [backgroundColor(Theme.Colors.blue400(opacity))]
let bgBlue500 = opacity => [backgroundColor(Theme.Colors.blue500(opacity))]
let bgBlue600 = opacity => [backgroundColor(Theme.Colors.blue600(opacity))]
let bgBlue700 = opacity => [backgroundColor(Theme.Colors.blue700(opacity))]
let bgBlue800 = opacity => [backgroundColor(Theme.Colors.blue800(opacity))]
let bgBlue900 = opacity => [backgroundColor(Theme.Colors.blue900(opacity))]

let bgIndigo50 = opacity => [backgroundColor(Theme.Colors.indigo50(opacity))]
let bgIndigo100 = opacity => [backgroundColor(Theme.Colors.indigo100(opacity))]
let bgIndigo200 = opacity => [backgroundColor(Theme.Colors.indigo200(opacity))]
let bgIndigo300 = opacity => [backgroundColor(Theme.Colors.indigo300(opacity))]
let bgIndigo400 = opacity => [backgroundColor(Theme.Colors.indigo400(opacity))]
let bgIndigo500 = opacity => [backgroundColor(Theme.Colors.indigo500(opacity))]
let bgIndigo600 = opacity => [backgroundColor(Theme.Colors.indigo600(opacity))]
let bgIndigo700 = opacity => [backgroundColor(Theme.Colors.indigo700(opacity))]
let bgIndigo800 = opacity => [backgroundColor(Theme.Colors.indigo800(opacity))]
let bgIndigo900 = opacity => [backgroundColor(Theme.Colors.indigo900(opacity))]

let bgViolet50 = opacity => [backgroundColor(Theme.Colors.violet50(opacity))]
let bgViolet100 = opacity => [backgroundColor(Theme.Colors.violet100(opacity))]
let bgViolet200 = opacity => [backgroundColor(Theme.Colors.violet200(opacity))]
let bgViolet300 = opacity => [backgroundColor(Theme.Colors.violet300(opacity))]
let bgViolet400 = opacity => [backgroundColor(Theme.Colors.violet400(opacity))]
let bgViolet500 = opacity => [backgroundColor(Theme.Colors.violet500(opacity))]
let bgViolet600 = opacity => [backgroundColor(Theme.Colors.violet600(opacity))]
let bgViolet700 = opacity => [backgroundColor(Theme.Colors.violet700(opacity))]
let bgViolet800 = opacity => [backgroundColor(Theme.Colors.violet800(opacity))]
let bgViolet900 = opacity => [backgroundColor(Theme.Colors.violet900(opacity))]

let bgPurple50 = opacity => [backgroundColor(Theme.Colors.purple50(opacity))]
let bgPurple100 = opacity => [backgroundColor(Theme.Colors.purple100(opacity))]
let bgPurple200 = opacity => [backgroundColor(Theme.Colors.purple200(opacity))]
let bgPurple300 = opacity => [backgroundColor(Theme.Colors.purple300(opacity))]
let bgPurple400 = opacity => [backgroundColor(Theme.Colors.purple400(opacity))]
let bgPurple500 = opacity => [backgroundColor(Theme.Colors.purple500(opacity))]
let bgPurple600 = opacity => [backgroundColor(Theme.Colors.purple600(opacity))]
let bgPurple700 = opacity => [backgroundColor(Theme.Colors.purple700(opacity))]
let bgPurple800 = opacity => [backgroundColor(Theme.Colors.purple800(opacity))]
let bgPurple900 = opacity => [backgroundColor(Theme.Colors.purple900(opacity))]

let bgFuchsia50 = opacity => [backgroundColor(Theme.Colors.fuchsia50(opacity))]
let bgFuchsia100 = opacity => [backgroundColor(Theme.Colors.fuchsia100(opacity))]
let bgFuchsia200 = opacity => [backgroundColor(Theme.Colors.fuchsia200(opacity))]
let bgFuchsia300 = opacity => [backgroundColor(Theme.Colors.fuchsia300(opacity))]
let bgFuchsia400 = opacity => [backgroundColor(Theme.Colors.fuchsia400(opacity))]
let bgFuchsia500 = opacity => [backgroundColor(Theme.Colors.fuchsia500(opacity))]
let bgFuchsia600 = opacity => [backgroundColor(Theme.Colors.fuchsia600(opacity))]
let bgFuchsia700 = opacity => [backgroundColor(Theme.Colors.fuchsia700(opacity))]
let bgFuchsia800 = opacity => [backgroundColor(Theme.Colors.fuchsia800(opacity))]
let bgFuchsia900 = opacity => [backgroundColor(Theme.Colors.fuchsia900(opacity))]

let bgPink50 = opacity => [backgroundColor(Theme.Colors.pink50(opacity))]
let bgPink100 = opacity => [backgroundColor(Theme.Colors.pink100(opacity))]
let bgPink200 = opacity => [backgroundColor(Theme.Colors.pink200(opacity))]
let bgPink300 = opacity => [backgroundColor(Theme.Colors.pink300(opacity))]
let bgPink400 = opacity => [backgroundColor(Theme.Colors.pink400(opacity))]
let bgPink500 = opacity => [backgroundColor(Theme.Colors.pink500(opacity))]
let bgPink600 = opacity => [backgroundColor(Theme.Colors.pink600(opacity))]
let bgPink700 = opacity => [backgroundColor(Theme.Colors.pink700(opacity))]
let bgPink800 = opacity => [backgroundColor(Theme.Colors.pink800(opacity))]
let bgPink900 = opacity => [backgroundColor(Theme.Colors.pink900(opacity))]

let bgRose50 = opacity => [backgroundColor(Theme.Colors.rose50(opacity))]
let bgRose100 = opacity => [backgroundColor(Theme.Colors.rose100(opacity))]
let bgRose200 = opacity => [backgroundColor(Theme.Colors.rose200(opacity))]
let bgRose300 = opacity => [backgroundColor(Theme.Colors.rose300(opacity))]
let bgRose400 = opacity => [backgroundColor(Theme.Colors.rose400(opacity))]
let bgRose500 = opacity => [backgroundColor(Theme.Colors.rose500(opacity))]
let bgRose600 = opacity => [backgroundColor(Theme.Colors.rose600(opacity))]
let bgRose700 = opacity => [backgroundColor(Theme.Colors.rose700(opacity))]
let bgRose800 = opacity => [backgroundColor(Theme.Colors.rose800(opacity))]
let bgRose900 = opacity => [backgroundColor(Theme.Colors.rose900(opacity))]
