open CssJs

// NOTE: Box Shadow - Utilities for controlling the box shadow of an element.
let shadowSm = [boxShadows(Theme.BoxShadow.sm)]
let shadow = [boxShadows(Theme.BoxShadow.default)]
let shadowMd = [boxShadows(Theme.BoxShadow.md)]
let shadowLg = [boxShadows(Theme.BoxShadow.lg)]
let shadowXl = [boxShadows(Theme.BoxShadow.xl)]
let shadow2Xl = [boxShadows(Theme.BoxShadow._2xl)]
let shadowInner = [boxShadows(Theme.BoxShadow.inner)]
let shadowNone = [boxShadow(#none)]

// NOTE: Opacity - Utilities for controlling the opacity of an element.
let opacity0 = [opacity(Theme.Opacity._0)]
let opacity5 = [opacity(Theme.Opacity._5)]
let opacity10 = [opacity(Theme.Opacity._10)]
let opacity15 = [opacity(Theme.Opacity._15)]
let opacity20 = [opacity(Theme.Opacity._20)]
let opacity25 = [opacity(Theme.Opacity._25)]
let opacity30 = [opacity(Theme.Opacity._30)]
let opacity35 = [opacity(Theme.Opacity._35)]
let opacity40 = [opacity(Theme.Opacity._40)]
let opacity45 = [opacity(Theme.Opacity._45)]
let opacity50 = [opacity(Theme.Opacity._50)]
let opacity55 = [opacity(Theme.Opacity._55)]
let opacity60 = [opacity(Theme.Opacity._60)]
let opacity65 = [opacity(Theme.Opacity._65)]
let opacity70 = [opacity(Theme.Opacity._70)]
let opacity75 = [opacity(Theme.Opacity._75)]
let opacity80 = [opacity(Theme.Opacity._80)]
let opacity85 = [opacity(Theme.Opacity._85)]
let opacity90 = [opacity(Theme.Opacity._90)]
let opacity95 = [opacity(Theme.Opacity._95)]
let opacity100 = [opacity(Theme.Opacity._100)]
