// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";

var Process = {};

var Path = {};

function readdirSync(path) {
  return Fs.readdirSync(path, {
              encoding: "utf-8",
              withFileTypes: false
            });
}

var Fs$1 = {
  readdirSync: readdirSync
};

export {
  Process ,
  Path ,
  Fs$1 as Fs,
  
}
/* fs Not a pure module */
