// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";

var Process = {};

var Path = {};

function statSync(bigintOpt, throwIfNoEntryOpt, string) {
  var bigint = bigintOpt !== undefined ? bigintOpt : false;
  var throwIfNoEntry = throwIfNoEntryOpt !== undefined ? throwIfNoEntryOpt : true;
  return Fs.statSync(string, {
              bigint: bigint,
              throwIfNoEntry: throwIfNoEntry
            });
}

function readdirSync(encodingOpt, withFileTypesOpt, path) {
  var encoding = encodingOpt !== undefined ? encodingOpt : "utf-8";
  var withFileTypes = withFileTypesOpt !== undefined ? withFileTypesOpt : false;
  return Fs.readdirSync(path, {
              encoding: encoding,
              withFileTypes: withFileTypes
            });
}

function readFileSync(encodingOpt, flagOpt, path) {
  var encoding = encodingOpt !== undefined ? encodingOpt : "utf-8";
  var flag = flagOpt !== undefined ? flagOpt : "r";
  return Fs.readFileSync(path, {
              encoding: encoding,
              flag: flag
            });
}

var Fs$1 = {
  statSync: statSync,
  readdirSync: readdirSync,
  readFileSync: readFileSync
};

export {
  Process ,
  Path ,
  Fs$1 as Fs,
  
}
/* fs Not a pure module */
