// Generated by ReScript, PLEASE EDIT WITH CARE


var Dark = {
  backgroundFill: "#1E293B",
  cardBorder: "#1E293B",
  redTextColor: "#F43F5E",
  darkSuitColor: "#F1F5F9"
};

var backgroundFill = "#F1F5F9";

var cardBorder = "#CBD5E1";

var redTextColor = "#EF4444";

var darkSuitColor = "#1E293B";

var strokeWidth = 2;

export {
  backgroundFill ,
  cardBorder ,
  redTextColor ,
  darkSuitColor ,
  strokeWidth ,
  Dark ,
  
}
/* No side effect */
