// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";

function useStopAnimationJank(param) {
  React.useEffect((function () {
          var resizeAnimationStopper = CssJs.style([CssJs.selector("*", [
                      CssJs.important(CssJs.transition(undefined, undefined, undefined, "none")),
                      CssJs.important(CssJs.animationPlayState("paused"))
                    ])]);
          var $$window$1 = window;
          var $$document$1 = document;
          var onResize = function (param) {
            var bodyCollection = $$document$1.getElementsByTagName("body");
            var body = bodyCollection.item(0);
            if (!(body == null)) {
              body.classList.add(resizeAnimationStopper);
            }
            setTimeout((function (param) {
                    if (!(body == null)) {
                      body.classList.remove(resizeAnimationStopper);
                      return ;
                    }
                    
                  }), 400);
            
          };
          $$window$1.addEventListener("resize", onResize);
          return (function (param) {
                    $$window$1.removeEventListener("resize", onResize);
                    
                  });
        }), []);
  
}

export {
  useStopAnimationJank ,
  
}
/* CssJs Not a pure module */
