// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactTestRenderer from "react-test-renderer";
import * as Css$RescriptMonorepo from "../styles/Css.mjs";
import * as Sum$RescriptMonorepo from "../Sum.mjs";
import * as Jest$RescriptMonorepo from "../bindings/Jest.mjs";
import * as Utils$RescriptMonorepo from "../utils/Utils.mjs";
import * as ResJest$RescriptMonorepo from "../ResJest.mjs";

function drinkAll(callback, flavour) {
  if (flavour !== "octopus") {
    return flavour;
  } else {
    return Curry._1(callback, flavour);
  }
}

var globalValue1 = {
  contents: 0
};

ResJest$RescriptMonorepo.describe("Snapshots", (function (param) {
        var styles = Css$RescriptMonorepo.declaration("float", "left");
        var Test = function (Props) {
          var children = Props.children;
          return React.createElement("h1", {
                      className: styles
                    }, children);
        };
        ResJest$RescriptMonorepo.test("renders with correct styles", (function (param) {
                var tree = ReactTestRenderer.create(React.createElement(Test, {
                            children: Utils$RescriptMonorepo.str("hello world")
                          })).toJSON();
                ResJest$RescriptMonorepo.expect(tree).toMatchSnapshot();
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Common Matchers", (function (param) {
        ResJest$RescriptMonorepo.test("toBe", (function (param) {
                ResJest$RescriptMonorepo.expect(Sum$RescriptMonorepo.sum(1, 2)).toBe(3);
                
              }));
        ResJest$RescriptMonorepo.test("two plus two is four", (function (param) {
                ResJest$RescriptMonorepo.expect(4).toBe(4);
                
              }));
        ResJest$RescriptMonorepo.test("two plus two is not five", (function (param) {
                ResJest$RescriptMonorepo.expect(4).not.toBe(5);
                
              }));
        ResJest$RescriptMonorepo.test("object assignment using rescript records", (function (param) {
                var dataUpdate = {
                  num: 2,
                  name: "test"
                };
                var dataMutable = {
                  name: "Baby",
                  age: 5
                };
                dataMutable.age = dataMutable.age + 1 | 0;
                ResJest$RescriptMonorepo.expect({
                        num: 1,
                        name: "test"
                      }).toEqual({
                      num: 1,
                      name: "test"
                    });
                ResJest$RescriptMonorepo.expect(dataUpdate).toEqual({
                      num: 2,
                      name: "test"
                    });
                ResJest$RescriptMonorepo.expect(dataMutable).toEqual({
                      name: "Baby",
                      age: 6
                    });
                
              }));
        ResJest$RescriptMonorepo.test("null", (function (param) {
                var $$null = null;
                ResJest$RescriptMonorepo.expect($$null).toBeDefined();
                ResJest$RescriptMonorepo.expect(undefined).not.toBeDefined();
                ResJest$RescriptMonorepo.expect($$null).toBeNull();
                ResJest$RescriptMonorepo.expect(undefined).not.toBeNull();
                ResJest$RescriptMonorepo.expect(undefined).toBeUndefined();
                ResJest$RescriptMonorepo.expect($$null).not.toBeUndefined();
                ResJest$RescriptMonorepo.expect(true).toBeTruthy();
                ResJest$RescriptMonorepo.expect($$null).not.toBeTruthy();
                ResJest$RescriptMonorepo.expect($$null).toBeFalsy();
                ResJest$RescriptMonorepo.expect(true).not.toBeFalsy();
                
              }));
        ResJest$RescriptMonorepo.test("zero", (function (param) {
                ResJest$RescriptMonorepo.expect(0).not.toBeNull();
                ResJest$RescriptMonorepo.expect(0).toBeDefined();
                ResJest$RescriptMonorepo.expect(0).not.toBeUndefined();
                ResJest$RescriptMonorepo.expect(0).not.toBeTruthy();
                ResJest$RescriptMonorepo.expect(0).toBeFalsy();
                
              }));
        ResJest$RescriptMonorepo.test("two plus two", (function (param) {
                ResJest$RescriptMonorepo.expect(4).toBeGreaterThan(3);
                ResJest$RescriptMonorepo.expect(4).toBeGreaterThanOrEqual(3.5);
                ResJest$RescriptMonorepo.expect(4).toBeLessThan(5);
                ResJest$RescriptMonorepo.expect(4).toBeLessThanOrEqual(4.5);
                ResJest$RescriptMonorepo.expect(4).toBe(4);
                ResJest$RescriptMonorepo.expect(4).toEqual(4);
                
              }));
        ResJest$RescriptMonorepo.test("adding floating point numbers", (function (param) {
                var value = 0.1 + 0.2;
                ResJest$RescriptMonorepo.expect(value).toBeCloseTo(0.3);
                
              }));
        ResJest$RescriptMonorepo.test("the shopping list has beer on it", (function (param) {
                var shoppingList = [
                  "diapers",
                  "kleenex",
                  "trash bags",
                  "paper towels",
                  "beer"
                ];
                ResJest$RescriptMonorepo.expect(shoppingList).toContain("beer");
                ResJest$RescriptMonorepo.expect(shoppingList).not.toContain("BEER");
                
              }));
        ResJest$RescriptMonorepo.test("there is no I in team", (function (param) {
                ResJest$RescriptMonorepo.expect("team").not.toMatch(/I/);
                
              }));
        ResJest$RescriptMonorepo.test("but there is a 'stop' in Christoph", (function (param) {
                ResJest$RescriptMonorepo.expect("Christoph").toMatch(/stop/);
                
              }));
        ResJest$RescriptMonorepo.test("id should match object", (function (param) {
                var obj = {
                  id: "111",
                  product: "Test",
                  url: "https://jestjs.io/"
                };
                ResJest$RescriptMonorepo.expect(obj).toEqual(expect.objectContaining({
                          id: "111"
                        }));
                ResJest$RescriptMonorepo.expect(obj).toEqual(expect.not.objectContaining({
                          title: "Test"
                        }));
                
              }));
        ResJest$RescriptMonorepo.test("String containing", (function (param) {
                ResJest$RescriptMonorepo.expect("abcdefghijk").toEqual(expect.stringContaining("abcde"));
                ResJest$RescriptMonorepo.expect("abcdefghijk").not.toEqual(expect.stringContaining("abce"));
                
              }));
        ResJest$RescriptMonorepo.test("String matching", (function (param) {
                ResJest$RescriptMonorepo.expect("abcdefghijk").toEqual(expect.stringContaining("abcde"));
                ResJest$RescriptMonorepo.expect("abcdefghijk").not.toEqual(expect.stringContaining("abce"));
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Array Containing", (function (param) {
        var expected = [
          "Alice",
          "Bob"
        ];
        ResJest$RescriptMonorepo.it("matches even if received contains additional elements", (function (param) {
                ResJest$RescriptMonorepo.expect([
                        "Alice",
                        "Bob",
                        "Eve"
                      ]).toEqual(expect.arrayContaining(expected));
                
              }));
        ResJest$RescriptMonorepo.it("matches even if received contains additional elements", (function (param) {
                ResJest$RescriptMonorepo.expect([
                        "Bob",
                        "Eve"
                      ]).toEqual(expect.not.arrayContaining(expected));
                
              }));
        ResJest$RescriptMonorepo.it("does not match if received does not contain expected elements", (function (param) {
                ResJest$RescriptMonorepo.expect([
                        "Bob",
                        "Eve"
                      ]).not.toEqual(expect.arrayContaining(expected));
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("stringMatching in arrayContaining", (function (param) {
        var expected = [
          expect.stringMatching(/^Alic/),
          expect.stringMatching(/^[BR]ob/)
        ];
        ResJest$RescriptMonorepo.it("matches even if received contains additional elements", (function (param) {
                ResJest$RescriptMonorepo.expect([
                        "Alicia",
                        "Roberto",
                        "Evelina"
                      ]).toEqual(expect.arrayContaining(expected));
                
              }));
        ResJest$RescriptMonorepo.it("does not match if received does not contain expected elements", (function (param) {
                ResJest$RescriptMonorepo.expect([
                        "Roberto",
                        "Evelina"
                      ]).not.toEqual(expect.arrayContaining(expected));
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Mock function", (function (param) {
        ResJest$RescriptMonorepo.test("drinks something lemon-flavoured", (function (param) {
                var mockFn = jest.fn();
                Curry._1(mockFn, undefined);
                return Jest$RescriptMonorepo.toHaveBeenCalled(ResJest$RescriptMonorepo.expect(mockFn), undefined);
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Mock function with implementation", (function (param) {
        ResJest$RescriptMonorepo.test("drinks something lemon-flavoured", (function (param) {
                var returnsTrue = jest.fn(function (param) {
                      return true;
                    });
                ResJest$RescriptMonorepo.expect(Curry._1(returnsTrue, undefined)).toBe(true);
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Lifecycle", (function (param) {
        var persistentValue = {
          contents: 0
        };
        ResJest$RescriptMonorepo.beforeEach(function (param) {
              persistentValue.contents = persistentValue.contents + 1 | 0;
              
            });
        ResJest$RescriptMonorepo.afterEach(function (param) {
              persistentValue.contents = persistentValue.contents - 1 | 0;
              
            });
        ResJest$RescriptMonorepo.test("runs lifecycle the first time", (function (param) {
                ResJest$RescriptMonorepo.expect(persistentValue.contents).toBe(1);
                
              }));
        ResJest$RescriptMonorepo.test("runs lifecycle each time", (function (param) {
                ResJest$RescriptMonorepo.expect(persistentValue.contents).toBe(1);
                
              }));
        
      }));

ResJest$RescriptMonorepo.describe("Skips other tests", (function (param) {
        var persistentValue = {
          contents: 0
        };
        ResJest$RescriptMonorepo.beforeEach(function (param) {
              persistentValue.contents = persistentValue.contents + 1 | 0;
              
            });
        ResJest$RescriptMonorepo.afterEach(function (param) {
              persistentValue.contents = persistentValue.contents - 1 | 0;
              
            });
        ResJest$RescriptMonorepo.testSkip("runs lifecycle the first time", (function (param) {
                ResJest$RescriptMonorepo.expect(persistentValue.contents).toBe(1);
                
              }));
        ResJest$RescriptMonorepo.test("runs lifecycle each time", (function (param) {
                ResJest$RescriptMonorepo.expect(persistentValue.contents).toBe(1);
                
              }));
        
      }));

ResJest$RescriptMonorepo.describeSkip("Lifecycle", (function (param) {
        var persistentValue = {
          contents: 0
        };
        beforeEach(function () {
              persistentValue.contents = persistentValue.contents + 1 | 0;
              
            });
        afterEach(function () {
              persistentValue.contents = persistentValue.contents - 1 | 0;
              
            });
        test("runs lifecycle the first time", (function () {
                expect(persistentValue.contents).toBe(1);
                
              }));
        test("runs lifecycle each time", (function () {
                expect(persistentValue.contents).toBe(1);
                
              }));
        
      }));

describe("Test each functionality", (function () {
        test.each([
                [
                  1,
                  1,
                  2
                ],
                [
                  1,
                  2,
                  3
                ],
                [
                  2,
                  1,
                  3
                ]
              ])(".add(%i, %i)", (function (a, b, expected) {
                expect(a + b | 0).toBe(expected);
                
              }));
        Jest$RescriptMonorepo.itEach([
                [
                  1,
                  1,
                  2
                ],
                [
                  1,
                  2,
                  3
                ],
                [
                  2,
                  1,
                  3
                ]
              ])(".add(%i, %i)", (function (a, b, expected) {
                expect(a + b | 0).toBe(expected);
                
              }));
        
      }));

describe("Test skip each", (function () {
        test.skip.each([
                [
                  1,
                  1,
                  2
                ],
                [
                  1,
                  2,
                  3
                ],
                [
                  2,
                  1,
                  3
                ]
              ])(".add(%i, %i)", (function (a, b, expected) {
                expect(a + b | 0).toBe(expected);
                
              }));
        
      }));

describe("Todo works", (function () {
        test.todo("Write test 1");
        test.todo("Write test 2");
        test.todo("Write test 3");
        
      }));

describe.each([
        [
          1,
          1,
          2
        ],
        [
          1,
          2,
          3
        ],
        [
          2,
          1,
          3
        ]
      ])(".add(%i, %i)", (function (a, b, expected) {
        test("returns " + String(expected), (function () {
                expect(a + b | 0).toBe(expected);
                
              }));
        test("returned value not be greater than " + String(expected), (function () {
                expect(a + b | 0).not.toBeGreaterThan(expected);
                
              }));
        test("returned value not be less than " + String(expected), (function () {
                expect(a + b | 0).not.toBeLessThan(expected);
                
              }));
        
      }));

var sum = Sum$RescriptMonorepo.sum;

export {
  sum ,
  drinkAll ,
  globalValue1 ,
  
}
/*  Not a pure module */
