// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Tailwind$RescriptMonorepo from "../../../../styles/tailwind/Tailwind.mjs";
import * as CardDefaults$RescriptMonorepo from "../CardDefaults.mjs";

var elementStyles = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.w("v20")]);

var Styles = {
  elementStyles: elementStyles
};

function DQ(Props) {
  var backgroundFillOpt = Props.backgroundFill;
  var cardBorderOpt = Props.cardBorder;
  var strokeWidthOpt = Props.strokeWidth;
  var cardTextColorOpt = Props.cardTextColor;
  var suitColorOpt = Props.suitColor;
  var backgroundFill = backgroundFillOpt !== undefined ? backgroundFillOpt : CardDefaults$RescriptMonorepo.backgroundFill;
  var cardBorder = cardBorderOpt !== undefined ? cardBorderOpt : CardDefaults$RescriptMonorepo.cardBorder;
  var strokeWidth = strokeWidthOpt !== undefined ? strokeWidthOpt : CardDefaults$RescriptMonorepo.strokeWidth;
  var cardTextColor = cardTextColorOpt !== undefined ? cardTextColorOpt : CardDefaults$RescriptMonorepo.redTextColor;
  var suitColor = suitColorOpt !== undefined ? suitColorOpt : CardDefaults$RescriptMonorepo.redTextColor;
  return React.createElement("svg", {
              className: elementStyles,
              fill: "none",
              viewBox: "0 0 348 462",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("g", {
                  filter: "url(#filter0_d)"
                }, React.createElement("rect", {
                      height: "394",
                      width: "280",
                      fill: backgroundFill,
                      rx: "20",
                      x: "34",
                      y: "29"
                    }), React.createElement("rect", {
                      height: "393",
                      width: "279",
                      rx: "19.5",
                      stroke: cardBorder,
                      strokeWidth: String(strokeWidth),
                      x: "34.5",
                      y: "29.5"
                    })), React.createElement("path", {
                  d: "M119.602 97.8516C119.602 103.164 118.742 107.786 117.023 111.719C115.305 115.625 112.922 118.763 109.875 121.133L119.328 128.555L111.867 135.156L99.7578 125.43C98.3776 125.664 96.9453 125.781 95.4609 125.781C90.7474 125.781 86.5417 124.648 82.8437 122.383C79.1458 120.117 76.2812 116.888 74.25 112.695C72.2187 108.477 71.1901 103.633 71.1641 98.1641V95.3516C71.1641 89.7526 72.1667 84.8307 74.1719 80.5859C76.2031 76.3151 79.0547 73.0469 82.7266 70.7812C86.4245 68.4896 90.6432 67.3437 95.3828 67.3437C100.122 67.3437 104.328 68.4896 108 70.7812C111.698 73.0469 114.549 76.3151 116.555 80.5859C118.586 84.8307 119.602 89.7396 119.602 95.3125V97.8516ZM107.727 95.2734C107.727 89.3099 106.659 84.7786 104.523 81.6797C102.388 78.5807 99.3411 77.0312 95.3828 77.0312C91.4505 77.0312 88.4167 78.5677 86.2812 81.6406C84.1458 84.6875 83.0651 89.1667 83.0391 95.0781V97.8516C83.0391 103.659 84.1068 108.164 86.2422 111.367C88.3776 114.57 91.4505 116.172 95.4609 116.172C99.3932 116.172 102.414 114.635 104.523 111.562C106.633 108.464 107.701 103.958 107.727 98.0469V95.2734Z",
                  fill: cardTextColor
                }), React.createElement("path", {
                  clipRule: "evenodd",
                  d: "M67.2307 185.628L96.5044 215.831L125.778 185.628L96.5044 155.425L67.2307 185.628Z",
                  fill: suitColor,
                  fillRule: "evenodd"
                }), React.createElement("defs", undefined, React.createElement("filter", {
                      id: "filter0_d",
                      height: "462",
                      width: "348",
                      colorInterpolationFilters: "sRGB",
                      filterUnits: "userSpaceOnUse",
                      x: "0",
                      y: "0"
                    }, React.createElement("feFlood", {
                          floodOpacity: "0",
                          result: "BackgroundImageFix"
                        }), React.createElement("feColorMatrix", {
                          type: "matrix",
                          in: "SourceAlpha",
                          values: "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                        }), React.createElement("feOffset", {
                          dy: "5"
                        }), React.createElement("feGaussianBlur", {
                          stdDeviation: "17"
                        }), React.createElement("feColorMatrix", {
                          type: "matrix",
                          values: "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"
                        }), React.createElement("feBlend", {
                          in2: "BackgroundImageFix",
                          mode: "normal",
                          result: "effect1_dropShadow"
                        }), React.createElement("feBlend", {
                          in: "SourceGraphic",
                          in2: "effect1_dropShadow",
                          mode: "normal",
                          result: "shape"
                        }))));
}

var make = DQ;

export {
  Styles ,
  make ,
  
}
/* elementStyles Not a pure module */
