// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(size) {
  if (size === "screenMd") {
    return {
            NAME: "px",
            VAL: 768
          };
  } else if (size === "screenSm") {
    return {
            NAME: "px",
            VAL: 640
          };
  } else if (size === "screenXl") {
    return {
            NAME: "px",
            VAL: 1280
          };
  } else if (size === "screenXl2") {
    return {
            NAME: "px",
            VAL: 1536
          };
  } else {
    return {
            NAME: "px",
            VAL: 1024
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
