// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(span) {
  if (span === 2) {
    return 2;
  } else if (span === 3) {
    return 3;
  } else if (span === 4) {
    return 4;
  } else if (span === 5) {
    return 5;
  } else if (span === 6) {
    return 6;
  } else if (span === 7) {
    return 7;
  } else {
    return 1;
  }
}

export {
  toValue ,
  
}
/* No side effect */
