// Generated by ReScript, PLEASE EDIT WITH CARE


function spanStr(value) {
  return "span " + String(value) + " / span " + String(value);
}

function toValue(span) {
  if (span === "v2") {
    return spanStr(2);
  } else if (span === "v3") {
    return spanStr(3);
  } else if (span === "v4") {
    return spanStr(4);
  } else if (span === "v5") {
    return spanStr(5);
  } else if (span === "v6") {
    return spanStr(6);
  } else {
    return spanStr(1);
  }
}

export {
  spanStr ,
  toValue ,
  
}
/* No side effect */
