// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(value) {
  if (value === "v5By12") {
    return {
            NAME: "percent",
            VAL: 41.666667
          };
  } else if (value === "v3By6" || value === "v2By4" || value === "v1By2" || value === "v6By12") {
    return {
            NAME: "percent",
            VAL: 50
          };
  } else if (value === "v7By12") {
    return {
            NAME: "percent",
            VAL: 58.333333
          };
  } else if (value === "v1By12") {
    return {
            NAME: "percent",
            VAL: 8.333333
          };
  } else if (value === "v5By6" || value === "v10By12") {
    return {
            NAME: "percent",
            VAL: 83.333333
          };
  } else if (value === "v3By12" || value === "v1By4") {
    return {
            NAME: "percent",
            VAL: 25
          };
  } else if (value === "v1By5") {
    return {
            NAME: "percent",
            VAL: 20
          };
  } else if (value === "v2By12" || value === "v1By6") {
    return {
            NAME: "percent",
            VAL: 16.666667
          };
  } else if (value === "v8By12" || value === "v4By6" || value === "v2By3") {
    return {
            NAME: "percent",
            VAL: 66.666667
          };
  } else if (value === "v2By5") {
    return {
            NAME: "percent",
            VAL: 40
          };
  } else if (value === "v9By12" || value === "v3By4") {
    return {
            NAME: "percent",
            VAL: 75
          };
  } else if (value === "v3By5") {
    return {
            NAME: "percent",
            VAL: 60
          };
  } else if (value === "v4By5") {
    return {
            NAME: "percent",
            VAL: 80
          };
  } else if (value === "v11By12") {
    return {
            NAME: "percent",
            VAL: 91.666667
          };
  } else {
    return {
            NAME: "percent",
            VAL: 33.333333
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
