// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(width) {
  if (width === "prose") {
    return {
            NAME: "ch",
            VAL: 65
          };
  } else if (width === "none") {
    return "none";
  } else if (width === "zero") {
    return {
            NAME: "rem",
            VAL: 0
          };
  } else if (width === "lg") {
    return {
            NAME: "rem",
            VAL: 32
          };
  } else if (width === "md") {
    return {
            NAME: "rem",
            VAL: 28
          };
  } else if (width === "sm") {
    return {
            NAME: "rem",
            VAL: 24
          };
  } else if (width === "xl") {
    return {
            NAME: "rem",
            VAL: 36
          };
  } else if (width === "xs") {
    return {
            NAME: "rem",
            VAL: 20
          };
  } else if (width === "xl2") {
    return {
            NAME: "rem",
            VAL: 42
          };
  } else if (width === "xl3") {
    return {
            NAME: "rem",
            VAL: 48
          };
  } else if (width === "xl4") {
    return {
            NAME: "rem",
            VAL: 56
          };
  } else if (width === "xl5") {
    return {
            NAME: "rem",
            VAL: 64
          };
  } else if (width === "xl6") {
    return {
            NAME: "rem",
            VAL: 72
          };
  } else if (width === "xl7") {
    return {
            NAME: "rem",
            VAL: 80
          };
  } else {
    return {
            NAME: "percent",
            VAL: 100
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
