// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(colStart) {
  if (colStart === 2) {
    return 2;
  } else if (colStart === 3) {
    return 3;
  } else if (colStart === 4) {
    return 4;
  } else if (colStart === 5) {
    return 5;
  } else if (colStart === 6) {
    return 6;
  } else if (colStart === 7) {
    return 7;
  } else if (colStart === 8) {
    return 8;
  } else if (colStart === 9) {
    return 9;
  } else if (colStart === 10) {
    return 10;
  } else if (colStart === 11) {
    return 11;
  } else if (colStart === 12) {
    return 12;
  } else if (colStart === 13) {
    return 13;
  } else {
    return 1;
  }
}

export {
  toValue ,
  
}
/* No side effect */
