// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(value) {
  if (value === 0) {
    return {
            NAME: "px",
            VAL: 0
          };
  } else if (value === 1) {
    return {
            NAME: "rem",
            VAL: 0.25
          };
  } else if (value === 2) {
    return {
            NAME: "rem",
            VAL: 0.5
          };
  } else if (value === 3) {
    return {
            NAME: "rem",
            VAL: 0.75
          };
  } else if (value === 4) {
    return {
            NAME: "rem",
            VAL: 1
          };
  } else if (value === 5) {
    return {
            NAME: "rem",
            VAL: 1.25
          };
  } else if (value === 6) {
    return {
            NAME: "rem",
            VAL: 1.5
          };
  } else if (value === 7) {
    return {
            NAME: "rem",
            VAL: 1.75
          };
  } else if (value === 8) {
    return {
            NAME: "rem",
            VAL: 2
          };
  } else if (value === 9) {
    return {
            NAME: "rem",
            VAL: 2.25
          };
  } else if (value === 10) {
    return {
            NAME: "rem",
            VAL: 2.5
          };
  } else if (value === 11) {
    return {
            NAME: "rem",
            VAL: 2.75
          };
  } else if (value === 12) {
    return {
            NAME: "rem",
            VAL: 3
          };
  } else if (value === 14) {
    return {
            NAME: "rem",
            VAL: 3.5
          };
  } else if (value === 16) {
    return {
            NAME: "rem",
            VAL: 4
          };
  } else if (value === 18) {
    return {
            NAME: "rem",
            VAL: 4.5
          };
  } else if (value === 20) {
    return {
            NAME: "rem",
            VAL: 5
          };
  } else if (value === 24) {
    return {
            NAME: "rem",
            VAL: 6
          };
  } else if (value === 28) {
    return {
            NAME: "rem",
            VAL: 7
          };
  } else if (value === 32) {
    return {
            NAME: "rem",
            VAL: 8
          };
  } else if (value === 36) {
    return {
            NAME: "rem",
            VAL: 9
          };
  } else if (value === 40) {
    return {
            NAME: "rem",
            VAL: 10
          };
  } else if (value === 44) {
    return {
            NAME: "rem",
            VAL: 11
          };
  } else if (value === 48) {
    return {
            NAME: "rem",
            VAL: 12
          };
  } else if (value === 52) {
    return {
            NAME: "rem",
            VAL: 13
          };
  } else if (value === 56) {
    return {
            NAME: "rem",
            VAL: 14
          };
  } else if (value === 60) {
    return {
            NAME: "rem",
            VAL: 15
          };
  } else if (value === 64) {
    return {
            NAME: "rem",
            VAL: 16
          };
  } else if (value === 68) {
    return {
            NAME: "rem",
            VAL: 17
          };
  } else if (value === 72) {
    return {
            NAME: "rem",
            VAL: 18
          };
  } else if (value === 76) {
    return {
            NAME: "rem",
            VAL: 19
          };
  } else if (value === 80) {
    return {
            NAME: "rem",
            VAL: 20
          };
  } else if (value === 84) {
    return {
            NAME: "rem",
            VAL: 21
          };
  } else if (value === 88) {
    return {
            NAME: "rem",
            VAL: 22
          };
  } else if (value === 92) {
    return {
            NAME: "rem",
            VAL: 23
          };
  } else if (value === 96) {
    return {
            NAME: "rem",
            VAL: 24
          };
  } else if (value === "px") {
    return {
            NAME: "px",
            VAL: 1
          };
  } else if (value === "0_5") {
    return {
            NAME: "rem",
            VAL: 0.125
          };
  } else if (value === 100) {
    return {
            NAME: "rem",
            VAL: 25
          };
  } else if (value === 104) {
    return {
            NAME: "rem",
            VAL: 26
          };
  } else if (value === 108) {
    return {
            NAME: "rem",
            VAL: 27
          };
  } else if (value === 112) {
    return {
            NAME: "rem",
            VAL: 28
          };
  } else if (value === 116) {
    return {
            NAME: "rem",
            VAL: 29
          };
  } else if (value === 120) {
    return {
            NAME: "rem",
            VAL: 30
          };
  } else if (value === 124) {
    return {
            NAME: "rem",
            VAL: 31
          };
  } else if (value === 128) {
    return {
            NAME: "rem",
            VAL: 32
          };
  } else if (value === 132) {
    return {
            NAME: "rem",
            VAL: 33
          };
  } else if (value === 136) {
    return {
            NAME: "rem",
            VAL: 34
          };
  } else if (value === 140) {
    return {
            NAME: "rem",
            VAL: 35
          };
  } else if (value === 144) {
    return {
            NAME: "rem",
            VAL: 36
          };
  } else if (value === 148) {
    return {
            NAME: "rem",
            VAL: 37
          };
  } else if (value === 152) {
    return {
            NAME: "rem",
            VAL: 38
          };
  } else if (value === 156) {
    return {
            NAME: "rem",
            VAL: 39
          };
  } else if (value === 160) {
    return {
            NAME: "rem",
            VAL: 40
          };
  } else if (value === 164) {
    return {
            NAME: "rem",
            VAL: 41
          };
  } else if (value === 168) {
    return {
            NAME: "rem",
            VAL: 42
          };
  } else if (value === 172) {
    return {
            NAME: "rem",
            VAL: 43
          };
  } else if (value === 176) {
    return {
            NAME: "rem",
            VAL: 44
          };
  } else if (value === 180) {
    return {
            NAME: "rem",
            VAL: 45
          };
  } else if (value === 184) {
    return {
            NAME: "rem",
            VAL: 46
          };
  } else if (value === 188) {
    return {
            NAME: "rem",
            VAL: 47
          };
  } else if (value === 192) {
    return {
            NAME: "rem",
            VAL: 48
          };
  } else if (value === 196) {
    return {
            NAME: "rem",
            VAL: 49
          };
  } else if (value === "1_5") {
    return {
            NAME: "rem",
            VAL: 0.375
          };
  } else if (value === 200) {
    return {
            NAME: "rem",
            VAL: 50
          };
  } else if (value === "2_5") {
    return {
            NAME: "rem",
            VAL: 0.625
          };
  } else if (value === "3_5") {
    return {
            NAME: "rem",
            VAL: 0.875
          };
  } else {
    return {
            NAME: "percent",
            VAL: 100
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
