// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(index) {
  if (index === 10) {
    return 10;
  } else if (index === 20) {
    return 20;
  } else if (index === 30) {
    return 30;
  } else if (index === 40) {
    return 40;
  } else if (index === 50) {
    return 50;
  } else if (index === 60) {
    return 60;
  } else if (index === 70) {
    return 70;
  } else if (index === 80) {
    return 80;
  } else if (index === 90) {
    return 90;
  } else if (index === 100) {
    return 100;
  } else {
    return 0;
  }
}

export {
  toValue ,
  
}
/* No side effect */
