// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(order) {
  if (order === "none") {
    return 0;
  } else if (order === 1) {
    return 1;
  } else if (order === 2) {
    return 2;
  } else if (order === 3) {
    return 3;
  } else if (order === 4) {
    return 4;
  } else if (order === 5) {
    return 5;
  } else if (order === 6) {
    return 6;
  } else if (order === 7) {
    return 7;
  } else if (order === 8) {
    return 8;
  } else if (order === 9) {
    return 9;
  } else if (order === 10) {
    return 10;
  } else if (order === 11) {
    return 11;
  } else if (order === 12) {
    return 12;
  } else if (order === "first") {
    return 9999;
  } else {
    return -9999;
  }
}

export {
  toValue ,
  
}
/* No side effect */
