// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(scale) {
  if (scale === "v105") {
    return 1.05;
  } else if (scale === "v110") {
    return 1.10;
  } else if (scale === "v125") {
    return 1.25;
  } else if (scale === "v150") {
    return 1.50;
  } else if (scale === "v0") {
    return 0;
  } else if (scale === "v50") {
    return 0.5;
  } else if (scale === "v75") {
    return 0.75;
  } else if (scale === "v90") {
    return 0.90;
  } else if (scale === "v95") {
    return 0.95;
  } else {
    return 1.00;
  }
}

export {
  toValue ,
  
}
/* No side effect */
