// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(fontSize) {
  if (fontSize === "lg") {
    return {
            NAME: "rem",
            VAL: 1.125
          };
  } else if (fontSize === "sm") {
    return {
            NAME: "rem",
            VAL: 0.875
          };
  } else if (fontSize === "xl") {
    return {
            NAME: "rem",
            VAL: 1.25
          };
  } else if (fontSize === "xs") {
    return {
            NAME: "rem",
            VAL: 0.75
          };
  } else if (fontSize === "xl2") {
    return {
            NAME: "rem",
            VAL: 1.5
          };
  } else if (fontSize === "xl3") {
    return {
            NAME: "rem",
            VAL: 1.875
          };
  } else if (fontSize === "xl4") {
    return {
            NAME: "rem",
            VAL: 2.25
          };
  } else if (fontSize === "xl5") {
    return {
            NAME: "rem",
            VAL: 3
          };
  } else if (fontSize === "xl6") {
    return {
            NAME: "rem",
            VAL: 3.75
          };
  } else if (fontSize === "xl7") {
    return {
            NAME: "rem",
            VAL: 4.5
          };
  } else if (fontSize === "xl8") {
    return {
            NAME: "rem",
            VAL: 6
          };
  } else if (fontSize === "xl9") {
    return {
            NAME: "rem",
            VAL: 8
          };
  } else {
    return {
            NAME: "rem",
            VAL: 1
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
