// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(rotate) {
  if (rotate === "neg2") {
    return {
            NAME: "deg",
            VAL: -2
          };
  } else if (rotate === "neg3") {
    return {
            NAME: "deg",
            VAL: -3
          };
  } else if (rotate === "neg6") {
    return {
            NAME: "deg",
            VAL: -6
          };
  } else if (rotate === "v180") {
    return {
            NAME: "deg",
            VAL: 180
          };
  } else if (rotate === "neg180") {
    return {
            NAME: "deg",
            VAL: -180
          };
  } else if (rotate === "v0") {
    return {
            NAME: "deg",
            VAL: 0
          };
  } else if (rotate === "v1") {
    return {
            NAME: "deg",
            VAL: 1
          };
  } else if (rotate === "v2") {
    return {
            NAME: "deg",
            VAL: 2
          };
  } else if (rotate === "v3") {
    return {
            NAME: "deg",
            VAL: 3
          };
  } else if (rotate === "v6") {
    return {
            NAME: "deg",
            VAL: 6
          };
  } else if (rotate === "v12") {
    return {
            NAME: "deg",
            VAL: 12
          };
  } else if (rotate === "v45") {
    return {
            NAME: "deg",
            VAL: 45
          };
  } else if (rotate === "v90") {
    return {
            NAME: "deg",
            VAL: 90
          };
  } else if (rotate === "neg12") {
    return {
            NAME: "deg",
            VAL: -12
          };
  } else if (rotate === "neg45") {
    return {
            NAME: "deg",
            VAL: -45
          };
  } else if (rotate === "neg90") {
    return {
            NAME: "deg",
            VAL: -90
          };
  } else {
    return {
            NAME: "deg",
            VAL: -1
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
