// Generated by ReScript, PLEASE EDIT WITH CARE


function toValue(lineHeight) {
  if (lineHeight === "snug") {
    return {
            NAME: "abs",
            VAL: 1.375
          };
  } else if (lineHeight === "relaxed") {
    return {
            NAME: "abs",
            VAL: 1.625
          };
  } else if (lineHeight === "loose") {
    return {
            NAME: "abs",
            VAL: 2
          };
  } else if (lineHeight === 3) {
    return {
            NAME: "rem",
            VAL: 0.75
          };
  } else if (lineHeight === 4) {
    return {
            NAME: "rem",
            VAL: 1
          };
  } else if (lineHeight === 5) {
    return {
            NAME: "rem",
            VAL: 1.25
          };
  } else if (lineHeight === 6) {
    return {
            NAME: "rem",
            VAL: 1.5
          };
  } else if (lineHeight === 7) {
    return {
            NAME: "rem",
            VAL: 1.75
          };
  } else if (lineHeight === 8) {
    return {
            NAME: "rem",
            VAL: 2
          };
  } else if (lineHeight === 9) {
    return {
            NAME: "rem",
            VAL: 2.25
          };
  } else if (lineHeight === 10) {
    return {
            NAME: "rem",
            VAL: 2.5
          };
  } else if (lineHeight === 11) {
    return {
            NAME: "rem",
            VAL: 2.75
          };
  } else if (lineHeight === 12) {
    return {
            NAME: "rem",
            VAL: 3
          };
  } else if (lineHeight === 13) {
    return {
            NAME: "rem",
            VAL: 3.25
          };
  } else if (lineHeight === 14) {
    return {
            NAME: "rem",
            VAL: 3.5
          };
  } else if (lineHeight === "tight") {
    return {
            NAME: "abs",
            VAL: 1.25
          };
  } else if (lineHeight === "normal") {
    return {
            NAME: "abs",
            VAL: 1.5
          };
  } else {
    return {
            NAME: "abs",
            VAL: 1
          };
  }
}

export {
  toValue ,
  
}
/* No side effect */
