// Generated by ReScript, PLEASE EDIT WITH CARE


function spanStr(value) {
  return "span " + String(value) + " / span " + String(value);
}

function toValue(span) {
  if (span === 2) {
    return spanStr(2);
  } else if (span === 3) {
    return spanStr(3);
  } else if (span === 4) {
    return spanStr(4);
  } else if (span === 5) {
    return spanStr(5);
  } else if (span === 6) {
    return spanStr(6);
  } else {
    return spanStr(1);
  }
}

export {
  spanStr ,
  toValue ,
  
}
/* No side effect */
