// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Utils$RescriptMonorepo from "../utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "../styles/tailwind/Tailwind.mjs";

var elementStyles = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("xl"),
      Tailwind$RescriptMonorepo.textColor(undefined, "blue700")
    ]);

var Styles = {
  elementStyles: elementStyles
};

function Demo(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: Tailwind$RescriptMonorepo.merge([
                    elementStyles,
                    className
                  ])
            }, Utils$RescriptMonorepo.str("Hello I'm demo component with some styles"));
}

var make = Demo;

export {
  Styles ,
  make ,
  
}
/* elementStyles Not a pure module */
