// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var Styles = {};

function Nav(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("nav", {
              className: className
            }, children);
}

var make = Nav;

export {
  Styles ,
  make ,
  
}
/* react Not a pure module */
