// Generated by ReScript, PLEASE EDIT WITH CARE


function str(a) {
  return a;
}

function clog(str) {
  console.log(str);
  
}

var copySymbol = "\u00a9";

var mdash = "\u2014";

var lsquo = "\u201C";

var nbsp = "\u00A0";

var grave = "\u0060";

var transmitState = "\u0094";

var rarr = "\u2192";

export {
  str ,
  clog ,
  copySymbol ,
  mdash ,
  lsquo ,
  nbsp ,
  grave ,
  transmitState ,
  rarr ,
  
}
/* No side effect */
