// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress$RescriptMonorepo from "../../src/bindings/Cypress.mjs";

Cypress$RescriptMonorepo.context("Traversal", (function (param) {
        Cypress$RescriptMonorepo.beforeEach(function (param) {
              cy.visit("https://example.cypress.io/commands/traversal", undefined);
              
            });
        Cypress$RescriptMonorepo.it(".children() - get child DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-breadcrumb", undefined).children(".active", undefined), "Data");
              }));
        Cypress$RescriptMonorepo.it(".closest() - get closest ancestor DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveClass(cy.get(".traversal-badge", undefined).closest("ul", undefined), "list-group");
              }));
        Cypress$RescriptMonorepo.it(".eq() - get a DOM element at a specific index", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-list>li", undefined).eq(1, undefined), "siamese");
              }));
        Cypress$RescriptMonorepo.it(".filter() - get DOM elements that match the selector", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-nav>li", undefined).filter(".active", undefined), "About");
              }));
        Cypress$RescriptMonorepo.it(".find() - get descendant DOM elements of the selector", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".traversal-pagination", undefined).find("li", undefined).find("a", undefined), 7);
              }));
        Cypress$RescriptMonorepo.it(".first() - get first DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-table td", undefined).first(undefined), "1");
              }));
        Cypress$RescriptMonorepo.it(".last() - get last DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-buttons .btn", undefined).last(undefined), "Submit");
              }));
        Cypress$RescriptMonorepo.it(".next() - get next sibling DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-ul", undefined).contains(undefined, "apples", undefined).next(undefined), "oranges");
              }));
        Cypress$RescriptMonorepo.it(".next() - get next sibling DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-ul", undefined).contains(undefined, "apples", undefined).next(Cypress$RescriptMonorepo.ChildrenOptions.make(undefined, undefined, undefined)), "oranges");
              }));
        Cypress$RescriptMonorepo.it(".nextAll() - get all next sibling DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".traversal-next-all", undefined).contains(undefined, "oranges", undefined).nextAll(undefined), 3);
              }));
        Cypress$RescriptMonorepo.it(".nextAll() - get all next sibling DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".traversal-next-all", undefined).contains(undefined, "oranges", undefined).nextAll(Cypress$RescriptMonorepo.ChildrenOptions.make(undefined, undefined, undefined)), 3);
              }));
        Cypress$RescriptMonorepo.it(".nextUntil() - get next sibling DOM elements until next el", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get("#veggies", undefined).nextUntil("#nuts", undefined, undefined), 3);
              }));
        Cypress$RescriptMonorepo.it(".nextUntil() - get next sibling DOM elements until next el", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get("#veggies", undefined).nextUntil("#nuts", undefined, undefined), 3);
              }));
        Cypress$RescriptMonorepo.it(".nextUntil() - get next sibling DOM elements until next el", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get("#veggies", undefined).nextUntil("#nuts", "ul", undefined), 0);
              }));
        Cypress$RescriptMonorepo.it(".not() - remove DOM elements from set of DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldNotContain(cy.get(".traversal-disabled .btn", undefined).not("[disabled]", undefined), "Disabled");
              }));
        Cypress$RescriptMonorepo.it(".parent() - get parent DOM element from DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".traversal-mark", undefined).parent(undefined), "Morbi leo risus");
              }));
        Cypress$RescriptMonorepo.it(".parents() - get parent DOM elements from DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldMatch(cy.get(".traversal-cite", undefined).parents(undefined), "blockquote");
              }));
        Cypress$RescriptMonorepo.it(".parentsUntil() - get parent DOM elements from DOM elements until el", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".clothes-nav", undefined).find(".active", undefined).parentsUntil(".clothes-nav", undefined, undefined), 2);
              }));
        Cypress$RescriptMonorepo.it(".prev() - get previous sibling DOM element", (function (param) {
                return Cypress$RescriptMonorepo.shouldContain(cy.get(".birds", undefined).find(".active", undefined).prev(undefined), "Lorikeets");
              }));
        Cypress$RescriptMonorepo.it(".prevAll() - get all previous sibling DOM elements", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".fruits-list", undefined).find(".third", undefined).prevAll(undefined), 2);
              }));
        Cypress$RescriptMonorepo.it(".prevUntil() - get all previous sibling DOM elements until el", (function (param) {
                return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".foods-list", undefined).find("#nuts", undefined).prevUntil("#veggies", undefined, undefined), 3);
              }));
        return Cypress$RescriptMonorepo.it(".siblings() - get all sibling DOM elements", (function (param) {
                      return Cypress$RescriptMonorepo.shouldHaveLength(cy.get(".traversal-pills .active", undefined).siblings(undefined), 2);
                    }));
      }));

export {
  
}
/*  Not a pure module */
