// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress$RescriptMonorepo from "../../src/bindings/Cypress.mjs";

Cypress$RescriptMonorepo.context("Misc", (function (param) {
        Cypress$RescriptMonorepo.beforeEach(function (param) {
              cy.visit("https://example.cypress.io/commands/misc", undefined);
              
            });
        Cypress$RescriptMonorepo.it(".end() - end the command chain", (function (param) {
                cy.get(".misc-table", undefined).within(function (param) {
                      cy.contains(undefined, "Cheryl", undefined).click(undefined).end();
                      cy.contains(undefined, "Charles", undefined).click(undefined);
                      
                    });
                
              }));
        Cypress$RescriptMonorepo.it("cy.exec() - execute a system command", (function (param) {
                cy.log("Platform " + Cypress.platform + " architecture " + Cypress.arch);
                console.log(Cypress.browser);
                console.log(Cypress.env("circle"));
                var envExists = function (envString) {
                  return envString !== undefined;
                };
                var isCircleOnWindows = Cypress.platform === "win32" && envExists(Cypress.env("circle"));
                console.log(isCircleOnWindows);
                if (isCircleOnWindows) {
                  cy.log("Skipping test on CircleCI");
                }
                var isShippable = Cypress.platform === "linux" && envExists(Cypress.env("shippable"));
                if (isShippable) {
                  cy.log("Skipping test on ShippableCI");
                }
                Cypress$RescriptMonorepo.shouldContain(cy.exec("echo Jane Lane", undefined).its("stdout", undefined), "Jane Lane");
                if (Cypress.platform === "win32") {
                  Cypress$RescriptMonorepo.shouldBeEmpty(cy.exec("print cypress.json", undefined).its("stderr", Cypress$RescriptMonorepo.ChildrenOptions.make(undefined, undefined, undefined)));
                } else {
                  Cypress$RescriptMonorepo.shouldBeEmpty(cy.exec("cat cypress.json", undefined).its("stderr", Cypress$RescriptMonorepo.ChildrenOptions.make(undefined, undefined, undefined)));
                  Cypress$RescriptMonorepo.shouldEqualInt(cy.exec("pwd", undefined).its("code", undefined), 0);
                }
                
              }));
        Cypress$RescriptMonorepo.it("cy.focused() - get the DOM element that has focus", (function (param) {
                cy.get(".misc-form", undefined).find("#name", undefined).click(undefined);
                Cypress$RescriptMonorepo.shouldHaveId(cy.focused(Cypress$RescriptMonorepo.ChildrenOptions.make(undefined, undefined, undefined)), "name");
                cy.get(".misc-form", undefined).find("#description", undefined).click(undefined);
                return Cypress$RescriptMonorepo.shouldHaveId(cy.focused(undefined), "description");
              }));
        Cypress$RescriptMonorepo.context("Cypress.Screenshot", (function (param) {
                Cypress$RescriptMonorepo.it("cy.screenshot() - take a screenshot", (function (param) {
                        cy.screenshot("my-image", undefined);
                        
                      }));
                return Cypress$RescriptMonorepo.it("Cypress.Screenshot.defaults() - change default config of screenshots", (function (param) {
                              var screenshotOptions = Cypress$RescriptMonorepo.ScreenshotDefaults.make([".foo"], "viewport", {
                                    x: 0,
                                    y: 0,
                                    width: 200,
                                    height: 200
                                  }, true, false, undefined, undefined, undefined, undefined);
                              Cypress.Screenshot.defaults(screenshotOptions);
                              
                            }));
              }));
        return Cypress$RescriptMonorepo.it("cy.wrap() - wrap an object", (function (param) {
                      return Cypress$RescriptMonorepo.andInclude(Cypress$RescriptMonorepo.shouldHavePropertyP(cy.wrap({
                                          foo: "bar"
                                        }), "foo"), "bar");
                    }));
      }));

export {
  
}
/*  Not a pure module */
