import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import path from 'path'
import {make as Layout} from '../src/layouts/TypographyLayout.mjs'
import { postFilePaths, root} from '../src/server/Mdx__helpers.mjs'

export default function Examples({posts}) {

  return   <Layout>
  <h1>Home Page</h1>
  <p>
    Click the link below to navigate to a page generated by{' '}
    <code>next-mdx-remote</code>.
  </p>
  <ul>
    {posts.map((post) => (
      <li key={post.filePath}>
        <Link
          as={`/posts/${post.filePath.replace(/\.mdx?$/, '')}`}
          href={`/posts/[slug]`}
        >
          <a>{post.data.title}</a>
        </Link>
      </li>
    ))}
  </ul>
</Layout>
}


export function getStaticProps() {
  const postsRaw = postFilePaths("blog")
  console.log(postsRaw)
  const posts = postsRaw.map((filePath) => {
    const source = fs.readFileSync(path.join(root, "data/blog", filePath))
    const { content, data } = matter(source)

    return {
      content,
      data,
      filePath,
    }
  })

  return { props: { posts } }
}