// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import $$Image from "next/image";
import * as Tailwind$RescriptMonorepo from "../../styles/tailwind/Tailwind.mjs";

function $$Image$1(Props) {
  var src = Props.src;
  var alt = Props.alt;
  var width = Props.width;
  var height = Props.height;
  var layout = Props.layout;
  var objectFit = Props.objectFit;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tmp = {
    src: src,
    alt: alt,
    className: Tailwind$RescriptMonorepo.merge([className])
  };
  if (width !== undefined) {
    tmp.width = width;
  }
  if (height !== undefined) {
    tmp.height = height;
  }
  if (layout !== undefined) {
    tmp.layout = layout;
  }
  if (objectFit !== undefined) {
    tmp.objectFit = objectFit;
  }
  return React.createElement($$Image, tmp);
}

var make = $$Image$1;

export {
  make ,
  
}
/* react Not a pure module */
