// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";
import Link from "next/link";
import $$Image from "next/image";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Utils$RescriptMonorepo from "../../utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "../../styles/tailwind/Tailwind.mjs";
import * as TypographyLayout$RescriptMonorepo from "../../layouts/TypographyLayout.mjs";

var proseFirstChild = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& >", [Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.mt(0)])])]);

var proseLastChild = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& >", [Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.mb(0)])])]);

var proseBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.mx("auto"),
      Tailwind$RescriptMonorepo.Typography.maxW(65),
      Tailwind$RescriptMonorepo.Typography.fontSize(14)
    ]);

var proseSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(16),
            Tailwind$RescriptMonorepo.Typography.leading(28, 16)
          ])]);

var proseLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(18),
            Tailwind$RescriptMonorepo.Typography.leading(32, 18)
          ])]);

var proseXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(24),
            Tailwind$RescriptMonorepo.Typography.leading(40, 24)
          ])]);

var prose = Tailwind$RescriptMonorepo.merge([
      proseBase,
      proseSm,
      proseLg,
      proseXl,
      proseFirstChild,
      proseLastChild
    ]);

var paragraphBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.Typography.leading(24, 14),
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray700"),
      Tailwind$RescriptMonorepo.Typography.my(16, 14)
    ]);

var paragraphSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.my(20, 16)])]);

var paragraphLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.my(24, 18)])]);

var paragraphXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.my(32, 24)])]);

var paragraph = Tailwind$RescriptMonorepo.merge([
      paragraphBase,
      paragraphSm,
      paragraphLg,
      paragraphXl
    ]);

var leadBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray600"),
      Tailwind$RescriptMonorepo.Typography.fontSize(18),
      Tailwind$RescriptMonorepo.Typography.my(16, 18),
      Tailwind$RescriptMonorepo.Typography.leading(28, 18)
    ]);

var leadSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(20),
            Tailwind$RescriptMonorepo.Typography.leading(32, 20),
            Tailwind$RescriptMonorepo.Typography.my(24, 20)
          ])]);

var leadLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(22),
            Tailwind$RescriptMonorepo.Typography.leading(32, 22),
            Tailwind$RescriptMonorepo.Typography.my(24, 22)
          ])]);

var leadXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(30),
            Tailwind$RescriptMonorepo.Typography.leading(44, 30),
            Tailwind$RescriptMonorepo.Typography.my(32, 30)
          ])]);

var lead = Tailwind$RescriptMonorepo.merge([
      leadBase,
      leadSm,
      leadLg,
      leadXl
    ]);

var link = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
      Tailwind$RescriptMonorepo.underline,
      Tailwind$RescriptMonorepo.fontWeight(500)
    ]);

var strong = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
      Tailwind$RescriptMonorepo.fontWeight(600)
    ]);

var removeTopMarginFromNextElement = Tailwind$RescriptMonorepo.selector("&& + *", [Tailwind$RescriptMonorepo.mt(0)]);

var hrBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.borderT(1),
      Tailwind$RescriptMonorepo.borderColor("coolGray200"),
      Tailwind$RescriptMonorepo.Typography.my(40, 14),
      removeTopMarginFromNextElement
    ]);

var hrSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.my(48, 16)])]);

var hrLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.my(56, 18)])]);

var hrXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.my(72, 24)])]);

var hr = Tailwind$RescriptMonorepo.merge([
      hrBase,
      hrSm,
      hrLg,
      hrXl
    ]);

var blockquoteBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.italic,
      Tailwind$RescriptMonorepo.borderColor("coolGray200"),
      Tailwind$RescriptMonorepo.fontWeight(500),
      Tailwind$RescriptMonorepo.borderL(4),
      Tailwind$RescriptMonorepo.selector("p", [
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
            Tailwind$RescriptMonorepo.firstOfType([Tailwind$RescriptMonorepo.before([Tailwind$RescriptMonorepo.contentOpen])]),
            Tailwind$RescriptMonorepo.lastOfType([Tailwind$RescriptMonorepo.after([Tailwind$RescriptMonorepo.contentClose])])
          ]),
      Tailwind$RescriptMonorepo.Typography.my(24, 18),
      Tailwind$RescriptMonorepo.Typography.pl(20, 18)
    ]);

var blockquoteSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.my(32, 20),
            Tailwind$RescriptMonorepo.Typography.pl(20, 20)
          ])]);

var blockquoteLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.my(40, 24),
            Tailwind$RescriptMonorepo.Typography.pl(24, 24)
          ])]);

var blockquoteXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.my(64, 36),
            Tailwind$RescriptMonorepo.Typography.pl(40, 36)
          ])]);

var blockquote = Tailwind$RescriptMonorepo.merge([
      blockquoteBase,
      blockquoteSm,
      blockquoteLg,
      blockquoteXl
    ]);

var codeBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.fontMono,
      Tailwind$RescriptMonorepo.Typography.fontSize(12),
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
      Tailwind$RescriptMonorepo.fontWeight(600),
      Tailwind$RescriptMonorepo.before([Tailwind$RescriptMonorepo.contentText(Utils$RescriptMonorepo.grave)]),
      Tailwind$RescriptMonorepo.after([Tailwind$RescriptMonorepo.contentText(Utils$RescriptMonorepo.grave)])
    ]);

var codeSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.fontSize(14)])]);

var codeLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.fontSize(16)])]);

var codeXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.fontSize(20)])]);

var code = Tailwind$RescriptMonorepo.merge([
      codeBase,
      codeSm,
      codeLg,
      codeXl
    ]);

var codeInsideH2Base = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(18)])]);

var codeInsideH2Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(21)])])]);

var codeInsideH2Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(26)])])]);

var codeInsideH2Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(42)])])]);

var codeInsideH3Base = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(16)])]);

var codeInsideH3Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(18)])])]);

var codeInsideH3Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(21)])])]);

var codeInsideH3Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& code", [Tailwind$RescriptMonorepo.Typography.fontSize(32)])])]);

var codeInsideH2 = Tailwind$RescriptMonorepo.merge([
      codeInsideH2Base,
      codeInsideH2Sm,
      codeInsideH2Lg,
      codeInsideH2Xl
    ]);

var codeInsideH3 = Tailwind$RescriptMonorepo.merge([
      codeInsideH3Base,
      codeInsideH3Sm,
      codeInsideH3Lg,
      codeInsideH3Xl
    ]);

var h1Base = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
      Tailwind$RescriptMonorepo.fontWeight(800),
      Tailwind$RescriptMonorepo.Typography.fontSize(30),
      Tailwind$RescriptMonorepo.Typography.leading(36, 30),
      Tailwind$RescriptMonorepo.Typography.mt(0, 30),
      Tailwind$RescriptMonorepo.Typography.mb(24, 30)
    ]);

var h1Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(36),
            Tailwind$RescriptMonorepo.Typography.leading(40, 36),
            Tailwind$RescriptMonorepo.Typography.mt(0, 36),
            Tailwind$RescriptMonorepo.Typography.mb(32, 36)
          ])]);

var h1Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(48),
            Tailwind$RescriptMonorepo.Typography.leading(48, 48),
            Tailwind$RescriptMonorepo.Typography.mt(0, 48),
            Tailwind$RescriptMonorepo.Typography.mb(40, 48)
          ])]);

var h1Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(64),
            Tailwind$RescriptMonorepo.Typography.leading(64, 64),
            Tailwind$RescriptMonorepo.Typography.mt(0, 64),
            Tailwind$RescriptMonorepo.Typography.mb(56, 64)
          ])]);

var h1 = Tailwind$RescriptMonorepo.merge([
      h1Base,
      h1Sm,
      h1Lg,
      h1Xl
    ]);

var h2Base = Tailwind$RescriptMonorepo.merge([
      Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
            Tailwind$RescriptMonorepo.fontWeight(700),
            Tailwind$RescriptMonorepo.Typography.fontSize(20),
            Tailwind$RescriptMonorepo.Typography.leading(28, 20),
            Tailwind$RescriptMonorepo.Typography.mt(32, 20),
            Tailwind$RescriptMonorepo.Typography.mb(16, 20),
            removeTopMarginFromNextElement
          ]),
      codeInsideH2
    ]);

var h2Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(24),
            Tailwind$RescriptMonorepo.Typography.leading(32, 24),
            Tailwind$RescriptMonorepo.Typography.mt(48, 24),
            Tailwind$RescriptMonorepo.Typography.mb(24, 24)
          ])]);

var h2Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(30),
            Tailwind$RescriptMonorepo.Typography.leading(40, 30),
            Tailwind$RescriptMonorepo.Typography.mt(56, 30),
            Tailwind$RescriptMonorepo.Typography.mb(32, 30)
          ])]);

var h2Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(48),
            Tailwind$RescriptMonorepo.Typography.leading(52, 48),
            Tailwind$RescriptMonorepo.Typography.mt(72, 48),
            Tailwind$RescriptMonorepo.Typography.mb(40, 48)
          ])]);

var h2 = Tailwind$RescriptMonorepo.merge([
      h2Base,
      h2Sm,
      h2Lg,
      h2Xl
    ]);

var h3Base = Tailwind$RescriptMonorepo.merge([
      Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
            Tailwind$RescriptMonorepo.fontWeight(600),
            Tailwind$RescriptMonorepo.Typography.fontSize(18),
            Tailwind$RescriptMonorepo.Typography.leading(28, 18),
            Tailwind$RescriptMonorepo.Typography.mt(28, 18),
            Tailwind$RescriptMonorepo.Typography.mb(8, 18),
            removeTopMarginFromNextElement
          ]),
      codeInsideH3
    ]);

var h3Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(20),
            Tailwind$RescriptMonorepo.Typography.leading(32, 20),
            Tailwind$RescriptMonorepo.Typography.mt(32, 20),
            Tailwind$RescriptMonorepo.Typography.mb(12, 20)
          ])]);

var h3Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(24),
            Tailwind$RescriptMonorepo.Typography.mt(40, 24),
            Tailwind$RescriptMonorepo.Typography.mb(16, 24),
            Tailwind$RescriptMonorepo.Typography.leading(36, 24)
          ])]);

var h3Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(36),
            Tailwind$RescriptMonorepo.Typography.mt(56, 36),
            Tailwind$RescriptMonorepo.Typography.mb(24, 36),
            Tailwind$RescriptMonorepo.Typography.leading(44, 36)
          ])]);

var h3 = Tailwind$RescriptMonorepo.merge([
      h3Base,
      h3Sm,
      h3Lg,
      h3Xl
    ]);

var h4Base = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.Typography.leading(20, 14),
      Tailwind$RescriptMonorepo.Typography.mt(20, 14),
      Tailwind$RescriptMonorepo.Typography.mb(8, 14),
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
      Tailwind$RescriptMonorepo.fontWeight(600),
      removeTopMarginFromNextElement
    ]);

var h4Sm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.mt(24, 16),
            Tailwind$RescriptMonorepo.Typography.mb(8, 16),
            Tailwind$RescriptMonorepo.Typography.leading(24, 16)
          ])]);

var h4Lg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.mt(32, 18),
            Tailwind$RescriptMonorepo.Typography.mb(8, 18),
            Tailwind$RescriptMonorepo.Typography.leading(28, 18)
          ])]);

var h4Xl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.mt(40, 24),
            Tailwind$RescriptMonorepo.Typography.mb(16, 24),
            Tailwind$RescriptMonorepo.Typography.leading(36, 24)
          ])]);

var h4 = Tailwind$RescriptMonorepo.merge([
      h4Base,
      h4Sm,
      h4Lg,
      h4Xl
    ]);

var preBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.overflowXAuto,
      Tailwind$RescriptMonorepo.bg(undefined, "coolGray800"),
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray200"),
      Tailwind$RescriptMonorepo.Typography.fontSize(12),
      Tailwind$RescriptMonorepo.Typography.leading(20, 12),
      Tailwind$RescriptMonorepo.Typography.my(20, 12),
      Tailwind$RescriptMonorepo.Typography.px(12, 12),
      Tailwind$RescriptMonorepo.Typography.py(8, 12),
      Tailwind$RescriptMonorepo.rounded("default"),
      Tailwind$RescriptMonorepo.selector("& code", [
            Tailwind$RescriptMonorepo.border(0),
            Tailwind$RescriptMonorepo.fontWeight(400),
            Tailwind$RescriptMonorepo.borderR(0),
            Tailwind$RescriptMonorepo.bg(undefined, "transparent"),
            Tailwind$RescriptMonorepo.p(0),
            Tailwind$RescriptMonorepo.fontFamilies([
                  {
                    NAME: "custom",
                    VAL: "ui-monospace"
                  },
                  {
                    NAME: "custom",
                    VAL: "SFMono-Regular"
                  },
                  {
                    NAME: "custom",
                    VAL: "Menlo"
                  },
                  {
                    NAME: "custom",
                    VAL: "Monaco"
                  },
                  {
                    NAME: "custom",
                    VAL: "Consolas"
                  },
                  {
                    NAME: "custom",
                    VAL: "Liberation Mono"
                  },
                  {
                    NAME: "custom",
                    VAL: "Courier New"
                  },
                  "monospace"
                ]),
            Tailwind$RescriptMonorepo.before([Tailwind$RescriptMonorepo.contentNone]),
            Tailwind$RescriptMonorepo.after([Tailwind$RescriptMonorepo.contentNone])
          ])
    ]);

var preSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(14),
            Tailwind$RescriptMonorepo.Typography.leading(24, 14),
            Tailwind$RescriptMonorepo.Typography.my(24, 14),
            Tailwind$RescriptMonorepo.Typography.px(16, 14),
            Tailwind$RescriptMonorepo.Typography.py(12, 14)
          ])]);

var preLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(16),
            Tailwind$RescriptMonorepo.Typography.leading(28, 16),
            Tailwind$RescriptMonorepo.Typography.my(32, 16),
            Tailwind$RescriptMonorepo.Typography.px(24, 16),
            Tailwind$RescriptMonorepo.Typography.py(16, 16),
            Tailwind$RescriptMonorepo.rounded("md")
          ])]);

var preXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(20),
            Tailwind$RescriptMonorepo.Typography.leading(36, 20),
            Tailwind$RescriptMonorepo.Typography.my(40, 20),
            Tailwind$RescriptMonorepo.Typography.px(32, 20),
            Tailwind$RescriptMonorepo.Typography.py(24, 20),
            Tailwind$RescriptMonorepo.rounded("lg")
          ])]);

var pre = Tailwind$RescriptMonorepo.merge([
      preBase,
      preSm,
      preLg,
      preXl
    ]);

var nestedListBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& ul, & ol", [Tailwind$RescriptMonorepo.Typography.my(8, 14)])]);

var nestedListSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& ul, & ol", [Tailwind$RescriptMonorepo.Typography.my(12, 16)])])]);

var nestedListLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& ul, & ol", [Tailwind$RescriptMonorepo.Typography.my(16, 18)])])]);

var nestedListXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& ul, & ol", [Tailwind$RescriptMonorepo.Typography.my(16, 24)])])]);

var nestedList = Tailwind$RescriptMonorepo.merge([
      nestedListBase,
      nestedListSm,
      nestedListLg,
      nestedListXl
    ]);

var listPaddingBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.Typography.my(16, 14)]);

var listPaddingSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.my(20, 16)])]);

var listPaddingLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.my(24, 18)])]);

var listPaddingXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.my(32, 24)])]);

var listPadding = Tailwind$RescriptMonorepo.merge([
      listPaddingBase,
      listPaddingSm,
      listPaddingLg,
      listPaddingXl
    ]);

var liBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.relative,
      Tailwind$RescriptMonorepo.textColor(undefined, "coolGray700"),
      Tailwind$RescriptMonorepo.Typography.my(4, 14),
      Tailwind$RescriptMonorepo.Typography.pl(22, 14),
      Tailwind$RescriptMonorepo.Typography.leading(24, 14),
      Tailwind$RescriptMonorepo.selector("& > *", [
            Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.Typography.mt(16, 14)]),
            Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.Typography.mb(16, 14)])
          ])
    ]);

var liSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.my(8, 16),
            Tailwind$RescriptMonorepo.selector("& > *", [
                  Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.Typography.mt(20, 16)]),
                  Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.Typography.mb(20, 16)])
                ])
          ])]);

var liLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.my(12, 18),
            Tailwind$RescriptMonorepo.selector("& > *", [
                  Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.Typography.mt(24, 18)]),
                  Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.Typography.mb(24, 18)])
                ])
          ])]);

var liXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.my(12, 24),
            Tailwind$RescriptMonorepo.selector("& > *", [
                  Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.Typography.mt(32, 24)]),
                  Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.Typography.mb(32, 24)])
                ])
          ])]);

var li = Tailwind$RescriptMonorepo.merge([
      liBase,
      liSm,
      liLg,
      liXl
    ]);

function olItemsBase(listStyleType) {
  var selectedType = listStyleType === "lowerAlpha" ? "lowerAlpha" : (
      listStyleType === "upperAlpha" ? "upperAlpha" : (
          listStyleType === "decimal" ? "decimal" : (
              listStyleType === "lowerRoman" ? "lowerRoman" : (
                  listStyleType === "lowerLatin" ? "lowerLatin" : (
                      listStyleType === "upperRoman" ? "upperRoman" : (
                          listStyleType === "upperLatin" ? "upperLatin" : "lowerGreek"
                        )
                    )
                )
            )
        )
    );
  return Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& > li", [Tailwind$RescriptMonorepo.before([
                          [CssJs.contentRules([
                                  {
                                    NAME: "counter",
                                    VAL: [
                                      "list-item",
                                      selectedType
                                    ]
                                  },
                                  {
                                    NAME: "text",
                                    VAL: "."
                                  }
                                ])],
                          Tailwind$RescriptMonorepo.absolute,
                          Tailwind$RescriptMonorepo.fontWeight(400),
                          Tailwind$RescriptMonorepo.textColor(undefined, "coolGray500"),
                          Tailwind$RescriptMonorepo.left(0)
                        ])])]);
}

var olItemsSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& > li", [Tailwind$RescriptMonorepo.Typography.pl(28, 16)])])]);

var olItemsLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& > li", [Tailwind$RescriptMonorepo.Typography.pl(30, 18)])])]);

var olItemsXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& > li", [Tailwind$RescriptMonorepo.Typography.pl(40, 24)])])]);

var olItems = Tailwind$RescriptMonorepo.merge([
      olItemsBase("decimal"),
      olItemsSm,
      olItemsLg,
      olItemsXl
    ]);

var ol = Tailwind$RescriptMonorepo.merge([
      listPadding,
      olItems,
      nestedList
    ]);

var ulElementsBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& > li", [
            Tailwind$RescriptMonorepo.Typography.pl(30, 18),
            Tailwind$RescriptMonorepo.before([
                  Tailwind$RescriptMonorepo.absolute,
                  Tailwind$RescriptMonorepo.contentText(""),
                  Tailwind$RescriptMonorepo.bg(undefined, "coolGray300"),
                  Tailwind$RescriptMonorepo.rounded("full"),
                  Tailwind$RescriptMonorepo.Typography.square(5, 14),
                  Tailwind$RescriptMonorepo.Typography.topCalc({
                        NAME: "sub",
                        VAL: [
                          24 / 2,
                          2.5
                        ]
                      }, 14),
                  Tailwind$RescriptMonorepo.Typography.left(3, 14)
                ])
          ])]);

var ulElementsSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& > li", [
                  Tailwind$RescriptMonorepo.Typography.pl(28, 16),
                  Tailwind$RescriptMonorepo.before([
                        Tailwind$RescriptMonorepo.Typography.square(6, 16),
                        Tailwind$RescriptMonorepo.Typography.topCalc({
                              NAME: "sub",
                              VAL: [
                                28 / 2,
                                3
                              ]
                            }, 16),
                        Tailwind$RescriptMonorepo.Typography.left(4, 16)
                      ])
                ])])]);

var ulElementsLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& > li", [
                  Tailwind$RescriptMonorepo.Typography.pl(30, 18),
                  Tailwind$RescriptMonorepo.before([
                        Tailwind$RescriptMonorepo.Typography.square(6, 18),
                        Tailwind$RescriptMonorepo.Typography.topCalc({
                              NAME: "sub",
                              VAL: [
                                32 / 2,
                                3
                              ]
                            }, 18),
                        Tailwind$RescriptMonorepo.Typography.left(4, 18)
                      ])
                ])])]);

var ulElementsXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& > li", [
                  Tailwind$RescriptMonorepo.Typography.pl(40, 24),
                  Tailwind$RescriptMonorepo.before([
                        Tailwind$RescriptMonorepo.Typography.square(8, 24),
                        Tailwind$RescriptMonorepo.Typography.topCalc({
                              NAME: "sub",
                              VAL: [
                                40 / 2,
                                4
                              ]
                            }, 24),
                        Tailwind$RescriptMonorepo.Typography.left(6, 24)
                      ])
                ])])]);

var ulElements = Tailwind$RescriptMonorepo.merge([
      ulElementsBase,
      ulElementsSm,
      ulElementsLg,
      ulElementsXl
    ]);

var liParagraphBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& > li p", [Tailwind$RescriptMonorepo.Typography.my(8, 14)])]);

var liParagraphSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& > li p", [Tailwind$RescriptMonorepo.Typography.my(12, 16)])])]);

var liParagraphLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& > li p", [Tailwind$RescriptMonorepo.Typography.my(16, 18)])])]);

var liParagraphXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& > li p", [Tailwind$RescriptMonorepo.Typography.my(20, 24)])])]);

var liParagraph = Tailwind$RescriptMonorepo.merge([
      liParagraphBase,
      liParagraphSm,
      liParagraphLg,
      liParagraphXl
    ]);

var ul = Tailwind$RescriptMonorepo.merge([
      listPadding,
      ulElements,
      liParagraph,
      nestedList
    ]);

var anyChild = Tailwind$RescriptMonorepo.selector("&& > *", [Tailwind$RescriptMonorepo.my(0)]);

var figureFigcaptionBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("&& figcaption", [
            Tailwind$RescriptMonorepo.Typography.fontSize(12),
            Tailwind$RescriptMonorepo.Typography.leading(16, 12),
            Tailwind$RescriptMonorepo.Typography.mt(8, 12),
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray500")
          ])]);

var figureFigcaptionSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("&& figcaption", [
                  Tailwind$RescriptMonorepo.Typography.fontSize(14),
                  Tailwind$RescriptMonorepo.Typography.leading(20, 14),
                  Tailwind$RescriptMonorepo.Typography.mt(12, 14)
                ])])]);

var figureFigcaptionLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("&& figcaption", [
                  Tailwind$RescriptMonorepo.Typography.fontSize(16),
                  Tailwind$RescriptMonorepo.Typography.leading(24, 16),
                  Tailwind$RescriptMonorepo.Typography.mt(16, 16)
                ])])]);

var figureFigcaptionXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("&& figcaption", [
                  Tailwind$RescriptMonorepo.Typography.fontSize(20),
                  Tailwind$RescriptMonorepo.Typography.leading(32, 20),
                  Tailwind$RescriptMonorepo.Typography.mt(20, 20)
                ])])]);

var figureFigcaption = Tailwind$RescriptMonorepo.merge([
      figureFigcaptionBase,
      figureFigcaptionSm,
      figureFigcaptionLg,
      figureFigcaptionXl
    ]);

var figureBase = Tailwind$RescriptMonorepo.merge([
      Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.Typography.my(24, 14),
            anyChild
          ]),
      figureFigcaption
    ]);

var figureSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.my(32, 16)])]);

var figureLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.my(32, 18)])]);

var figureXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.my(48, 24)])]);

var figure = Tailwind$RescriptMonorepo.merge([
      figureBase,
      figureSm,
      figureLg,
      figureXl
    ]);

var imgBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.Typography.my(24, 14)]);

var imgSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.Typography.my(32, 16)])]);

var imgLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.Typography.my(32, 18)])]);

var imgXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.Typography.my(48, 24)])]);

var img = Tailwind$RescriptMonorepo.merge([
      imgBase,
      imgSm,
      imgLg,
      imgXl
    ]);

var tableBase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.Typography.fontSize(12),
      Tailwind$RescriptMonorepo.Typography.leading(18, 12),
      Tailwind$RescriptMonorepo.Typography.my(24, 12),
      Tailwind$RescriptMonorepo.w("full"),
      Tailwind$RescriptMonorepo.tableAuto,
      Tailwind$RescriptMonorepo.textLeft
    ]);

var tableSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.Typography.fontSize(14),
            Tailwind$RescriptMonorepo.Typography.leading(24, 14)
          ])]);

var tableLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([
            Tailwind$RescriptMonorepo.Typography.fontSize(16),
            Tailwind$RescriptMonorepo.Typography.leading(24, 16)
          ])]);

var tableXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([
            Tailwind$RescriptMonorepo.Typography.fontSize(20),
            Tailwind$RescriptMonorepo.Typography.leading(28, 20)
          ])]);

var table = Tailwind$RescriptMonorepo.merge([
      tableBase,
      tableSm,
      tableLg,
      tableXl
    ]);

var theadThBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& th", [
            Tailwind$RescriptMonorepo.Typography.px(12, 12),
            Tailwind$RescriptMonorepo.Typography.pb(8, 12),
            Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.pl(0)]),
            Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.pr(0)]),
            Tailwind$RescriptMonorepo.alignBottom
          ])]);

var theadThSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& th", [
                  Tailwind$RescriptMonorepo.Typography.px(8, 14),
                  Tailwind$RescriptMonorepo.Typography.pb(8, 14)
                ])])]);

var theadThLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& th", [
                  Tailwind$RescriptMonorepo.Typography.px(12, 16),
                  Tailwind$RescriptMonorepo.Typography.pb(12, 16)
                ])])]);

var theadThXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& th", [
                  Tailwind$RescriptMonorepo.Typography.px(12, 20),
                  Tailwind$RescriptMonorepo.Typography.pb(16, 20)
                ])])]);

var theadTh = Tailwind$RescriptMonorepo.merge([
      theadThBase,
      theadThSm,
      theadThLg,
      theadThXl
    ]);

var thead = Tailwind$RescriptMonorepo.merge([
      theadTh,
      Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray900"),
            Tailwind$RescriptMonorepo.fontWeight(600),
            Tailwind$RescriptMonorepo.borderB(1),
            Tailwind$RescriptMonorepo.borderColor("coolGray300")
          ])
    ]);

var tbodyTdBase = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("& td", [
            Tailwind$RescriptMonorepo.Typography.px(12, 12),
            Tailwind$RescriptMonorepo.Typography.py(8, 12),
            Tailwind$RescriptMonorepo.alignTop,
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray700"),
            Tailwind$RescriptMonorepo.firstChild([Tailwind$RescriptMonorepo.pl(0)]),
            Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.pr(0)])
          ])]);

var tbodyTdSm = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.sm([Tailwind$RescriptMonorepo.selector("& td", [
                  Tailwind$RescriptMonorepo.Typography.py(8, 14),
                  Tailwind$RescriptMonorepo.Typography.px(8, 14)
                ])])]);

var tbodyTdLg = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.lg([Tailwind$RescriptMonorepo.selector("& td", [
                  Tailwind$RescriptMonorepo.Typography.py(12, 16),
                  Tailwind$RescriptMonorepo.Typography.px(12, 16)
                ])])]);

var tbodyTdXl = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.xl([Tailwind$RescriptMonorepo.selector("& td", [
                  Tailwind$RescriptMonorepo.Typography.py(16, 20),
                  Tailwind$RescriptMonorepo.Typography.px(12, 20)
                ])])]);

var tbodyTd = Tailwind$RescriptMonorepo.merge([
      tbodyTdBase,
      tbodyTdSm,
      tbodyTdLg,
      tbodyTdXl
    ]);

var tbodyTr = Tailwind$RescriptMonorepo.selector("& tr", [
      Tailwind$RescriptMonorepo.borderB(1),
      Tailwind$RescriptMonorepo.borderColor("coolGray300"),
      Tailwind$RescriptMonorepo.lastChild([Tailwind$RescriptMonorepo.borderB(0)])
    ]);

var tbody = Tailwind$RescriptMonorepo.merge([
      tbodyTd,
      Tailwind$RescriptMonorepo.twStyle([tbodyTr])
    ]);

var Styles = {
  base: 14,
  baseSm: 16,
  baseLg: 18,
  baseXl: 24,
  proseFirstChild: proseFirstChild,
  proseLastChild: proseLastChild,
  proseBase: proseBase,
  proseSm: proseSm,
  proseLg: proseLg,
  proseXl: proseXl,
  prose: prose,
  paragraphBase: paragraphBase,
  paragraphSm: paragraphSm,
  paragraphLg: paragraphLg,
  paragraphXl: paragraphXl,
  paragraph: paragraph,
  rebaseLead: 18,
  rebaseLeadSm: 20,
  rebaseLeadLg: 22,
  rebaseLeadXl: 30,
  leadBase: leadBase,
  leadSm: leadSm,
  leadLg: leadLg,
  leadXl: leadXl,
  lead: lead,
  link: link,
  strong: strong,
  removeTopMarginFromNextElement: removeTopMarginFromNextElement,
  hrBase: hrBase,
  hrSm: hrSm,
  hrLg: hrLg,
  hrXl: hrXl,
  hr: hr,
  rebaseBlockquote: 18,
  rebaseBlockquoteSm: 20,
  rebaseBlockquoteLg: 24,
  rebaseBlockquoteXl: 36,
  blockquoteBase: blockquoteBase,
  blockquoteSm: blockquoteSm,
  blockquoteLg: blockquoteLg,
  blockquoteXl: blockquoteXl,
  blockquote: blockquote,
  rebaseCode: 12,
  rebaseCodeSm: 14,
  rebaseCodeLg: 16,
  rebaseCodeXl: 20,
  codeBase: codeBase,
  codeSm: codeSm,
  codeLg: codeLg,
  codeXl: codeXl,
  code: code,
  codeInsideH2Base: codeInsideH2Base,
  codeInsideH2Sm: codeInsideH2Sm,
  codeInsideH2Lg: codeInsideH2Lg,
  codeInsideH2Xl: codeInsideH2Xl,
  codeInsideH3Base: codeInsideH3Base,
  codeInsideH3Sm: codeInsideH3Sm,
  codeInsideH3Lg: codeInsideH3Lg,
  codeInsideH3Xl: codeInsideH3Xl,
  codeInsideH2: codeInsideH2,
  codeInsideH3: codeInsideH3,
  rebaseH1: 30,
  rebaseH1Sm: 36,
  rebaseH1Lg: 48,
  rebaseH1Xl: 64,
  h1Base: h1Base,
  h1Sm: h1Sm,
  h1Lg: h1Lg,
  h1Xl: h1Xl,
  h1: h1,
  rebaseH2: 20,
  rebaseH2Sm: 24,
  rebaseH2Lg: 30,
  rebaseH2Xl: 48,
  h2Base: h2Base,
  h2Sm: h2Sm,
  h2Lg: h2Lg,
  h2Xl: h2Xl,
  h2: h2,
  rebaseH3: 18,
  rebaseH3Sm: 20,
  rebaseH3Lg: 24,
  rebaseH3Xl: 36,
  h3Base: h3Base,
  h3Sm: h3Sm,
  h3Lg: h3Lg,
  h3Xl: h3Xl,
  h3: h3,
  h4Base: h4Base,
  h4Sm: h4Sm,
  h4Lg: h4Lg,
  h4Xl: h4Xl,
  h4: h4,
  rebasePre: 12,
  rebasePreSm: 14,
  rebasePreLg: 16,
  rebasePreXl: 20,
  preBase: preBase,
  preSm: preSm,
  preLg: preLg,
  preXl: preXl,
  pre: pre,
  nestedListBase: nestedListBase,
  nestedListSm: nestedListSm,
  nestedListLg: nestedListLg,
  nestedListXl: nestedListXl,
  nestedList: nestedList,
  listPaddingBase: listPaddingBase,
  listPaddingSm: listPaddingSm,
  listPaddingLg: listPaddingLg,
  listPaddingXl: listPaddingXl,
  listPadding: listPadding,
  liBase: liBase,
  liSm: liSm,
  liLg: liLg,
  liXl: liXl,
  li: li,
  olItemsBase: olItemsBase,
  olItemsSm: olItemsSm,
  olItemsLg: olItemsLg,
  olItemsXl: olItemsXl,
  olItems: olItems,
  ol: ol,
  ulElementsBase: ulElementsBase,
  ulElementsSm: ulElementsSm,
  ulElementsLg: ulElementsLg,
  ulElementsXl: ulElementsXl,
  ulElements: ulElements,
  liParagraphBase: liParagraphBase,
  liParagraphSm: liParagraphSm,
  liParagraphLg: liParagraphLg,
  liParagraphXl: liParagraphXl,
  liParagraph: liParagraph,
  ul: ul,
  anyChild: anyChild,
  rebaseFigcaption: 12,
  rebaseFigcaptionSm: 14,
  rebaseFigcaptionLg: 16,
  rebaseFigcaptionXl: 20,
  figureFigcaptionBase: figureFigcaptionBase,
  figureFigcaptionSm: figureFigcaptionSm,
  figureFigcaptionLg: figureFigcaptionLg,
  figureFigcaptionXl: figureFigcaptionXl,
  figureFigcaption: figureFigcaption,
  figureBase: figureBase,
  figureSm: figureSm,
  figureLg: figureLg,
  figureXl: figureXl,
  figure: figure,
  imgBase: imgBase,
  imgSm: imgSm,
  imgLg: imgLg,
  imgXl: imgXl,
  img: img,
  rebaseTable: 12,
  rebaseTableSm: 14,
  rebaseTableLg: 16,
  rebaseTableXl: 20,
  tableBase: tableBase,
  tableSm: tableSm,
  tableLg: tableLg,
  tableXl: tableXl,
  table: table,
  theadThBase: theadThBase,
  theadThSm: theadThSm,
  theadThLg: theadThLg,
  theadThXl: theadThXl,
  theadTh: theadTh,
  thead: thead,
  tbodyTdBase: tbodyTdBase,
  tbodyTdSm: tbodyTdSm,
  tbodyTdLg: tbodyTdLg,
  tbodyTdXl: tbodyTdXl,
  tbodyTd: tbodyTd,
  tbodyTr: tbodyTr,
  tbody: tbody
};

function Mdx$lead(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("p", {
              className: Tailwind$RescriptMonorepo.merge([
                    lead,
                    className
                  ])
            }, children);
}

function Mdx$wrapper(Props) {
  var children = Props.children;
  return React.createElement(TypographyLayout$RescriptMonorepo.make, {
              children: React.createElement("article", undefined, React.createElement("div", {
                        className: Tailwind$RescriptMonorepo.merge([prose])
                      }, children))
            });
}

function Mdx$p(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("p", {
              className: Tailwind$RescriptMonorepo.merge([
                    paragraph,
                    className
                  ])
            }, children);
}

function Mdx$h1(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("h1", {
              className: Tailwind$RescriptMonorepo.merge([
                    h2,
                    className
                  ])
            }, children);
}

function Mdx$h2(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("h2", {
              className: Tailwind$RescriptMonorepo.merge([
                    h2,
                    className
                  ])
            }, children);
}

function Mdx$h3(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("h3", {
              className: Tailwind$RescriptMonorepo.merge([
                    h3,
                    className
                  ])
            }, children);
}

function Mdx$h4(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("h4", {
              className: Tailwind$RescriptMonorepo.merge([
                    h4,
                    className
                  ])
            }, children);
}

function Mdx$blockquote(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("blockquote", {
              className: Tailwind$RescriptMonorepo.merge([
                    blockquote,
                    className
                  ])
            }, children);
}

function Mdx$ul(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("ul", {
              className: Tailwind$RescriptMonorepo.merge([
                    ul,
                    className
                  ])
            }, children);
}

function Mdx$ol(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("ol", {
              className: Tailwind$RescriptMonorepo.merge([
                    ol,
                    className
                  ])
            }, children);
}

function Mdx$li(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("li", {
              className: Tailwind$RescriptMonorepo.merge([
                    li,
                    className
                  ])
            }, children);
}

function Mdx$pre(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("pre", {
              className: Tailwind$RescriptMonorepo.merge([
                    pre,
                    className
                  ])
            }, React.createElement("code", undefined, children));
}

function Mdx$inlineCode(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("code", {
              className: Tailwind$RescriptMonorepo.merge([
                    code,
                    className
                  ])
            }, children);
}

function Mdx$em(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("em", {
              className: className
            }, children);
}

function Mdx$strong(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("strong", {
              className: Tailwind$RescriptMonorepo.merge([
                    strong,
                    className
                  ])
            }, children);
}

function Mdx$hr(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("hr", {
              className: Tailwind$RescriptMonorepo.merge([
                    hr,
                    className
                  ])
            });
}

function Mdx$a(Props) {
  var children = Props.children;
  var hrefOpt = Props.href;
  var classNameOpt = Props.className;
  var ariaLabelOpt = Props.ariaLabel;
  var href = hrefOpt !== undefined ? hrefOpt : "/";
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var ariaLabel = ariaLabelOpt !== undefined ? ariaLabelOpt : "";
  if ("/".startsWith(href)) {
    return React.createElement(Link, {
                href: href,
                children: React.createElement("a", {
                      "aria-label": ariaLabel,
                      className: Tailwind$RescriptMonorepo.merge([
                            link,
                            className
                          ])
                    }, children)
              });
  } else if ("#".startsWith(href)) {
    return React.createElement("a", {
                "aria-label": ariaLabel,
                className: Tailwind$RescriptMonorepo.merge([
                      link,
                      className
                    ]),
                href: href
              }, children);
  } else {
    return React.createElement("a", {
                "aria-label": ariaLabel,
                className: Tailwind$RescriptMonorepo.merge([
                      link,
                      className
                    ]),
                href: href,
                rel: "noopener noreferrer",
                target: "_blank"
              }, children);
  }
}

function Mdx$img(Props) {
  var src = Props.src;
  var altOpt = Props.alt;
  var classNameOpt = Props.className;
  var figcaption = Props.figcaption;
  var alt = altOpt !== undefined ? altOpt : "";
  var className = classNameOpt !== undefined ? classNameOpt : "";
  if (figcaption !== undefined) {
    return React.createElement("figure", {
                className: figure
              }, React.createElement($$Image, {
                    src: src,
                    alt: alt,
                    width: 1920,
                    height: 1271,
                    className: Tailwind$RescriptMonorepo.merge([
                          img,
                          className
                        ])
                  }), React.createElement("figcaption", undefined, Caml_option.valFromOption(figcaption)));
  } else {
    return React.createElement("figure", {
                className: figure
              }, React.createElement($$Image, {
                    src: src,
                    alt: alt,
                    width: 1920,
                    height: 1271,
                    className: Tailwind$RescriptMonorepo.merge([
                          img,
                          className
                        ])
                  }));
  }
}

function Mdx$table(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("table", {
              className: Tailwind$RescriptMonorepo.merge([
                    table,
                    className
                  ])
            }, children);
}

function Mdx$thead(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("thead", {
              className: Tailwind$RescriptMonorepo.merge([
                    thead,
                    className
                  ])
            }, children);
}

function Mdx$tbody(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("tbody", {
              className: Tailwind$RescriptMonorepo.merge([
                    tbody,
                    className
                  ])
            }, children);
}

function Mdx$tr(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("tr", {
              className: className
            }, children);
}

function Mdx$td(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("td", {
              className: className
            }, children);
}

var lead$1 = Mdx$lead;

var wrapper = Mdx$wrapper;

var p = Mdx$p;

var h1$1 = Mdx$h1;

var h2$1 = Mdx$h2;

var h3$1 = Mdx$h3;

var h4$1 = Mdx$h4;

var blockquote$1 = Mdx$blockquote;

var ul$1 = Mdx$ul;

var ol$1 = Mdx$ol;

var li$1 = Mdx$li;

var pre$1 = Mdx$pre;

var inlineCode = Mdx$inlineCode;

var em = Mdx$em;

var strong$1 = Mdx$strong;

var hr$1 = Mdx$hr;

var a = Mdx$a;

var img$1 = Mdx$img;

var table$1 = Mdx$table;

var thead$1 = Mdx$thead;

var tbody$1 = Mdx$tbody;

var tr = Mdx$tr;

var td = Mdx$td;

export {
  Styles ,
  lead$1 as lead,
  wrapper ,
  p ,
  h1$1 as h1,
  h2$1 as h2,
  h3$1 as h3,
  h4$1 as h4,
  blockquote$1 as blockquote,
  ul$1 as ul,
  ol$1 as ol,
  li$1 as li,
  pre$1 as pre,
  inlineCode ,
  em ,
  strong$1 as strong,
  hr$1 as hr,
  a ,
  img$1 as img,
  table$1 as table,
  thead$1 as thead,
  tbody$1 as tbody,
  tr ,
  td ,
  
}
/* proseFirstChild Not a pure module */
