// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Tailwind$RescriptMonorepo from "../../styles/tailwind/Tailwind.mjs";

var elementStyles = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("xl3"),
      Tailwind$RescriptMonorepo.fontWeight("v800"),
      Tailwind$RescriptMonorepo.tracking("tight"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray900"),
      Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.text("xl4"),
            Tailwind$RescriptMonorepo.leading("v10")
          ]),
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.text("xl5"),
            Tailwind$RescriptMonorepo.leading("v14")
          ])
    ]);

var Styles = {
  elementStyles: elementStyles
};

function PageTitle(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("h1", {
              className: Tailwind$RescriptMonorepo.merge([
                    elementStyles,
                    className
                  ])
            }, children);
}

var make = PageTitle;

export {
  Styles ,
  make ,
  
}
/* elementStyles Not a pure module */
