// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";
import * as Router from "next/router";
import * as Utils$RescriptMonorepo from "../../utils/Utils.mjs";
import * as SiteMetadata$RescriptMonorepo from "../../data/SiteMetadata.mjs";

function SEO$PageSEO(Props) {
  var title = Props.title;
  var description = Props.description;
  var router = Router.useRouter();
  return React.createElement(Head, {
              children: null
            }, React.createElement("title", undefined, Utils$RescriptMonorepo.str(title)), React.createElement("meta", {
                  content: "follow, index",
                  name: "robots"
                }), React.createElement("meta", {
                  content: description,
                  name: "description"
                }), React.createElement("meta", {
                  content: SiteMetadata$RescriptMonorepo.metadata.siteUrl + router.asPath,
                  property: "og:url"
                }), React.createElement("meta", {
                  content: "website",
                  property: "og:type"
                }), React.createElement("meta", {
                  content: SiteMetadata$RescriptMonorepo.metadata.title,
                  property: "og:site_name"
                }), React.createElement("meta", {
                  content: description,
                  property: "og:description"
                }), React.createElement("meta", {
                  content: title,
                  property: "og:title"
                }), React.createElement("meta", {
                  content: SiteMetadata$RescriptMonorepo.metadata.siteUrl + SiteMetadata$RescriptMonorepo.metadata.socialBanner,
                  property: "og:image"
                }), React.createElement("meta", {
                  content: "summary_large_image",
                  name: "twitter:card"
                }), React.createElement("meta", {
                  content: SiteMetadata$RescriptMonorepo.metadata.twitter,
                  name: "twitter:site"
                }), React.createElement("meta", {
                  content: title,
                  name: "twitter:title"
                }), React.createElement("meta", {
                  content: description,
                  name: "twitter:description"
                }), React.createElement("meta", {
                  content: SiteMetadata$RescriptMonorepo.metadata.siteUrl + SiteMetadata$RescriptMonorepo.metadata.socialBanner,
                  name: "twitter:image"
                }));
}

var PageSEO = {
  make: SEO$PageSEO
};

export {
  PageSEO ,
  
}
/* react Not a pure module */
