// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", undefined);
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
