// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as SEO$RescriptMonorepo from "./components/blog/SEO.mjs";
import * as ListLayout$RescriptMonorepo from "./layouts/ListLayout.mjs";
import * as Mdx__helpers$RescriptMonorepo from "./server/Mdx__helpers.mjs";
import * as SiteMetadata$RescriptMonorepo from "./data/SiteMetadata.mjs";

function $$default(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(SEO$RescriptMonorepo.PageSEO.make, {
                  title: "Blog - " + SiteMetadata$RescriptMonorepo.metadata.author,
                  description: SiteMetadata$RescriptMonorepo.metadata.description
                }), React.createElement(ListLayout$RescriptMonorepo.make, {
                  posts: props.posts,
                  title: "All Posts",
                  initialDisplayPosts: props.initialDisplayPosts,
                  pagination: props.pagination
                }));
}

function getStaticProps(_ctx) {
  var posts = Mdx__helpers$RescriptMonorepo.getBlogPostsFromLatest(undefined, undefined, undefined);
  var initialDisplayPosts = posts.slice(0, 5);
  var pagination_totalPages = Js_math.ceil(posts.length / 5);
  var pagination = {
    currentPage: 1,
    totalPages: pagination_totalPages
  };
  var props = {
    initialDisplayPosts: initialDisplayPosts,
    posts: posts,
    pagination: pagination
  };
  return Promise.resolve({
              props: props
            });
}

export {
  $$default ,
  $$default as default,
  getStaticProps ,
  
}
/* react Not a pure module */
