// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$RescriptMonorepo from "./components/blog/Link.mjs";
import * as Utils$RescriptMonorepo from "./utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "./styles/tailwind/Tailwind.mjs";
import * as Theme__Colors$RescriptMonorepo from "./styles/theme/private_modules/Theme__Colors.mjs";

var wrapper = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.flex,
      Tailwind$RescriptMonorepo.flexCol,
      Tailwind$RescriptMonorepo.itemsCenter,
      Tailwind$RescriptMonorepo.justifyStart,
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.justifyCenter,
            Tailwind$RescriptMonorepo.itemsCenter,
            Tailwind$RescriptMonorepo.flexRow,
            Tailwind$RescriptMonorepo.spaceX(6),
            Tailwind$RescriptMonorepo.mt(24)
          ])
    ]);

var titleSection = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.pt(6),
      Tailwind$RescriptMonorepo.pb(8),
      Tailwind$RescriptMonorepo.spaceX(2),
      Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.spaceY(5)])
    ]);

var h1 = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("xl6"),
      Tailwind$RescriptMonorepo.fontWeight(800),
      Tailwind$RescriptMonorepo.leading(9),
      Tailwind$RescriptMonorepo.tracking("tight"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray900"),
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.text("xl8"),
            Tailwind$RescriptMonorepo.leading(14),
            Tailwind$RescriptMonorepo.borderR(2),
            Tailwind$RescriptMonorepo.px(6)
          ]),
      Tailwind$RescriptMonorepo.dark([
            Tailwind$RescriptMonorepo.textColor(undefined, "gray100"),
            Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.borderColor(undefined, "gray700")])
          ])
    ]);

var maxW = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.maxW("md"),
      Tailwind$RescriptMonorepo.flex,
      Tailwind$RescriptMonorepo.flexCol,
      Tailwind$RescriptMonorepo.itemsCenter
    ]);

var p1 = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.mb(4),
      Tailwind$RescriptMonorepo.text("xl"),
      Tailwind$RescriptMonorepo.fontWeight(700),
      Tailwind$RescriptMonorepo.leading("normal"),
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.text("xl2"),
            Tailwind$RescriptMonorepo.textLeft
          ]),
      Tailwind$RescriptMonorepo.textCenter
    ]);

var p2 = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.mb(8),
      Tailwind$RescriptMonorepo.textCenter,
      Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.textLeft])
    ]);

var backIcon = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.h(8),
      Tailwind$RescriptMonorepo.w(8),
      Tailwind$RescriptMonorepo.inline,
      Tailwind$RescriptMonorepo.mr(2),
      Tailwind$RescriptMonorepo.mb("1_5"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray300")
    ]);

var button = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.inline,
      Tailwind$RescriptMonorepo.px(4),
      Tailwind$RescriptMonorepo.py(2),
      Tailwind$RescriptMonorepo.text("sm"),
      Tailwind$RescriptMonorepo.fontWeight(600),
      Tailwind$RescriptMonorepo.leading(5),
      Tailwind$RescriptMonorepo.borderColor(undefined, "transparent"),
      Tailwind$RescriptMonorepo.rounded("lg"),
      Tailwind$RescriptMonorepo.bg(undefined, "gray900"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray100"),
      Tailwind$RescriptMonorepo.hover([Tailwind$RescriptMonorepo.bg(undefined, "gray800")]),
      Tailwind$RescriptMonorepo.focus([Tailwind$RescriptMonorepo.ring(undefined, undefined, undefined, undefined, Theme__Colors$RescriptMonorepo.toColor(undefined, "gray700"))]),
      Tailwind$RescriptMonorepo.dark([
            Tailwind$RescriptMonorepo.border(1),
            Tailwind$RescriptMonorepo.borderColor(undefined, "gray100"),
            Tailwind$RescriptMonorepo.focus([Tailwind$RescriptMonorepo.ring(undefined, undefined, undefined, undefined, Theme__Colors$RescriptMonorepo.toColor(undefined, "gray600"))])
          ])
    ]);

var link = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.noUnderline]);

function FourZeroFour$BackIcon(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: className,
              fill: "currentColor",
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("path", {
                  d: "M0 0h24v24H0z",
                  fill: "none"
                }), React.createElement("path", {
                  d: "M10 9V5l-7 7 7 7v-4.1c5 0 8.5 1.6 11 5.1-1-5-4-10-11-11z"
                }));
}

function $$default(param) {
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("div", {
                  className: titleSection
                }, React.createElement("h1", {
                      className: h1
                    }, Utils$RescriptMonorepo.str("404"))), React.createElement("div", {
                  className: maxW
                }, React.createElement("p", {
                      className: p1
                    }, Utils$RescriptMonorepo.str("Sorry we couldn't find this page.")), React.createElement("p", {
                      className: p2
                    }, Utils$RescriptMonorepo.str("But dont worry, you can find plenty of other things on our homepage.")), React.createElement(Link$RescriptMonorepo.make, {
                      children: React.createElement("button", {
                            className: button
                          }, React.createElement(FourZeroFour$BackIcon, {
                                className: backIcon
                              }), Utils$RescriptMonorepo.str("Back to homepage")),
                      href: "/",
                      className: link
                    })));
}

export {
  $$default ,
  $$default as default,
  
}
/* wrapper Not a pure module */
