// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Mdx$RescriptMonorepo from "./components/Mdx.mjs";
import * as Utils$RescriptMonorepo from "./utils/Utils.mjs";
import * as Matrix$RescriptMonorepo from "./components/matrix/Matrix.mjs";
import * as Tailwind$RescriptMonorepo from "./styles/tailwind/Tailwind.mjs";

var container = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.mx("auto")]);

var header = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.textCenter]);

var Styles = {
  container: container,
  header: header
};

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: container
                }, React.createElement(Mdx$RescriptMonorepo.h2, {
                      children: Utils$RescriptMonorepo.str("Range Explorer"),
                      className: header
                    }), React.createElement(Matrix$RescriptMonorepo.make, {})));
}

export {
  Styles ,
  $$default ,
  $$default as default,
  
}
/* container Not a pure module */
