// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SEO$RescriptMonorepo from "./components/blog/SEO.mjs";
import * as Card$RescriptMonorepo from "./components/blog/Card.mjs";
import * as Utils$RescriptMonorepo from "./utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "./styles/tailwind/Tailwind.mjs";
import * as ProjectsData$RescriptMonorepo from "./data/ProjectsData.mjs";
import * as SiteMetadata$RescriptMonorepo from "./data/SiteMetadata.mjs";

var mainWrapper = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.dividers([
            Tailwind$RescriptMonorepo.divideY(undefined, "gray200", 1),
            Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.divideY(undefined, "gray700", 1)])
          ])]);

var titleSection = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.pt(6),
      Tailwind$RescriptMonorepo.pb(8),
      Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.dividers([Tailwind$RescriptMonorepo.spaceY(5)])])
    ]);

var h1 = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("xl3"),
      Tailwind$RescriptMonorepo.fontWeight(800),
      Tailwind$RescriptMonorepo.leading(9),
      Tailwind$RescriptMonorepo.tracking("tight"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray900"),
      Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.textColor(undefined, "gray100")]),
      Tailwind$RescriptMonorepo.sm([
            Tailwind$RescriptMonorepo.text("xl4"),
            Tailwind$RescriptMonorepo.leading(10)
          ]),
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.text("xl6"),
            Tailwind$RescriptMonorepo.leading(14)
          ])
    ]);

var showcase = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("lg"),
      Tailwind$RescriptMonorepo.leading(7),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray500"),
      Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.textColor(undefined, "gray400")])
    ]);

var container = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.container,
      Tailwind$RescriptMonorepo.py(12)
    ]);

var flexWrapper = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.flex,
      Tailwind$RescriptMonorepo.flexWrap,
      Tailwind$RescriptMonorepo.nm(4)
    ]);

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(SEO$RescriptMonorepo.PageSEO.make, {
                  title: "Projects - " + SiteMetadata$RescriptMonorepo.metadata.author,
                  description: SiteMetadata$RescriptMonorepo.metadata.description
                }), React.createElement("div", {
                  className: mainWrapper
                }, React.createElement("div", {
                      className: titleSection
                    }, React.createElement("h1", {
                          className: h1
                        }, Utils$RescriptMonorepo.str("Projects")), React.createElement("p", {
                          className: showcase
                        }, Utils$RescriptMonorepo.str("Showcase your projects with a hero image (16 x 9)"))), React.createElement("div", {
                      className: container
                    }, React.createElement("div", {
                          className: flexWrapper
                        }, ProjectsData$RescriptMonorepo.projectsData.map(function (project) {
                              return React.createElement(Card$RescriptMonorepo.make, {
                                          title: project.title,
                                          description: project.description,
                                          imgSrc: project.imgSrc,
                                          href: project.href,
                                          key: project.title
                                        });
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* mainWrapper Not a pure module */
