// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bundler$RescriptMonorepo from "./server/Bundler.mjs";

function getStaticProps(_ctx) {
  return Bundler$RescriptMonorepo.getFileBySlugNew(undefined, undefined, "introducing-tailwind-nextjs-starter-blog").then(function (value) {
              return Promise.resolve({
                          props: value
                        });
            });
}

export {
  getStaticProps ,
  
}
/* Bundler-RescriptMonorepo Not a pure module */
