// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import GrayMatter from "gray-matter";
import RemarkMath from "remark-math";
import RehypeKatex from "rehype-katex";
import * as Serialize from "next-mdx-remote/serialize";
import * as Mdx__helpers$RescriptMonorepo from "./server/Mdx__helpers.mjs";

function getStaticProps(param) {
  var slug = param.params.slug;
  var slugWithBlog = ["/blog"].concat(slug);
  var path = Mdx__helpers$RescriptMonorepo.join([
        Mdx__helpers$RescriptMonorepo.root,
        "data",
        "blog"
      ]);
  var allPosts = Mdx__helpers$RescriptMonorepo.getAllFrontMatter(path);
  var postIndex = allPosts.findIndex(function (post) {
        return post.slug === slugWithBlog.join("/");
      });
  var value = Belt_Array.get(allPosts, postIndex + 1 | 0);
  var prev = value !== undefined ? value : null;
  var value$1 = Belt_Array.get(allPosts, postIndex - 1 | 0);
  var next = value$1 !== undefined ? value$1 : null;
  var post = Mdx__helpers$RescriptMonorepo.getFileBySlug(undefined, slugWithBlog);
  var match = GrayMatter(post);
  var data = match.data;
  var value$2 = data.authors;
  var authorList = (value$2 == null) ? ["sensei"] : value$2;
  var authorData = authorList.map(function (val) {
        var authorResults = Mdx__helpers$RescriptMonorepo.getFileBySlug(undefined, [
              "authors",
              val
            ]);
        return GrayMatter(authorResults).data;
      });
  var __x = Serialize.serialize(match.content, {
        scope: data,
        mdxOptions: {
          remarkPlugins: [RemarkMath],
          rehypePlugins: [RehypeKatex],
          compilers: []
        },
        target: ["esnext"]
      });
  return __x.then(function (value) {
              var props = {
                path: slug,
                post: value,
                prev: prev,
                next: next,
                authorsArray: authorData
              };
              return Promise.resolve({
                          props: props
                        });
            });
}

export {
  getStaticProps ,
  
}
/* gray-matter Not a pure module */
