// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Css from "@emotion/css";
import * as Css$RescriptMonorepo from "./styles/Css.mjs";
import * as SEO$RescriptMonorepo from "./components/blog/SEO.mjs";
import * as Tag$RescriptMonorepo from "./components/blog/Tag.mjs";
import * as Link$RescriptMonorepo from "./components/blog/Link.mjs";
import * as Utils$RescriptMonorepo from "./utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "./styles/tailwind/Tailwind.mjs";
import * as Mdx__helpers$RescriptMonorepo from "./server/Mdx__helpers.mjs";
import * as SiteMetadata$RescriptMonorepo from "./data/SiteMetadata.mjs";

var pageWrapper = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.flex,
      Tailwind$RescriptMonorepo.flexCol,
      Tailwind$RescriptMonorepo.itemsStart,
      Tailwind$RescriptMonorepo.justifyStart,
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.justifyCenter,
            Tailwind$RescriptMonorepo.itemsCenter,
            Tailwind$RescriptMonorepo.flexRow,
            Tailwind$RescriptMonorepo.spaceX(6),
            Tailwind$RescriptMonorepo.mt(24)
          ]),
      Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.divideY(undefined, "gray700", 1)])
    ]);

var titleContainer = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.pt(6),
      Tailwind$RescriptMonorepo.pb(8),
      Tailwind$RescriptMonorepo.spaceX(2),
      Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.spaceY(5)])
    ]);

var h1Small = Css$RescriptMonorepo.sm(Tailwind$RescriptMonorepo.twStyle([
          Tailwind$RescriptMonorepo.text("xl4"),
          Tailwind$RescriptMonorepo.leading(10)
        ]));

var h1New = Css$RescriptMonorepo.color("FF00FF");

var h1New2 = Css$RescriptMonorepo.responsiveBreakpoint(440, Css$RescriptMonorepo.colorRaw("FF0000"), undefined, undefined);

var h1 = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.text("xl3"),
      Tailwind$RescriptMonorepo.fontWeight(800),
      Tailwind$RescriptMonorepo.leading(9),
      Tailwind$RescriptMonorepo.tracking("tight"),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray900"),
      Tailwind$RescriptMonorepo.md([
            Tailwind$RescriptMonorepo.text("xl6"),
            Tailwind$RescriptMonorepo.leading(14),
            Tailwind$RescriptMonorepo.borderR(2),
            Tailwind$RescriptMonorepo.px(6)
          ]),
      Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.textColor(undefined, "gray100")])
    ]);

var tagsSection = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.mt(2),
      Tailwind$RescriptMonorepo.mb(2),
      Tailwind$RescriptMonorepo.mr(5)
    ]);

var tagsWrapper = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.flex,
      Tailwind$RescriptMonorepo.flexWrap,
      Tailwind$RescriptMonorepo.maxW("lg"),
      Tailwind$RescriptMonorepo.borderT(1),
      Tailwind$RescriptMonorepo.borderColor(undefined, "gray300"),
      Tailwind$RescriptMonorepo.dark([
            Tailwind$RescriptMonorepo.borderColor(undefined, "gray700"),
            Tailwind$RescriptMonorepo.md([Tailwind$RescriptMonorepo.borderT(0)])
          ])
    ]);

var linkStyles = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.nml(2),
      Tailwind$RescriptMonorepo.text("sm"),
      Tailwind$RescriptMonorepo.fontWeight(600),
      Tailwind$RescriptMonorepo.textColor(undefined, "gray600"),
      Tailwind$RescriptMonorepo.uppercase,
      Tailwind$RescriptMonorepo.noUnderline,
      Tailwind$RescriptMonorepo.dark([Tailwind$RescriptMonorepo.textColor(undefined, "gray300")])
    ]);

function $$default(param) {
  var byValue = function (tuple1, tuple2) {
    return tuple2[1] - tuple1[1] | 0;
  };
  var entries = Js_dict.entries(param.tags);
  var sortedTags = entries.sort(byValue);
  console.log(sortedTags);
  console.log(h1New2);
  var notTagsMsg = entries.length === 0 ? React.createElement(React.Fragment, undefined, Utils$RescriptMonorepo.str("No tags found.")) : null;
  var renderTags = sortedTags.map(function (param) {
        var key = param[0];
        return React.createElement("div", {
                    key: key,
                    className: tagsSection
                  }, React.createElement(Tag$RescriptMonorepo.make, {
                        text: key
                      }), React.createElement(Link$RescriptMonorepo.make, {
                        children: Utils$RescriptMonorepo.str("(" + String(param[1]) + ")"),
                        href: "/tags/" + key,
                        className: linkStyles
                      }));
      });
  return React.createElement(React.Fragment, undefined, React.createElement(SEO$RescriptMonorepo.PageSEO.make, {
                  title: "Tags - " + SiteMetadata$RescriptMonorepo.metadata.author,
                  description: "Things I blog about"
                }), React.createElement("div", {
                  className: pageWrapper
                }, React.createElement("div", {
                      className: titleContainer
                    }, React.createElement("h1", {
                          className: Css.cx([
                                h1,
                                h1Small
                              ])
                        }, Utils$RescriptMonorepo.str("Tags")), React.createElement("h1", {
                          className: Css.cx([
                                h1New,
                                h1New2
                              ])
                        }, Utils$RescriptMonorepo.str("Tags"))), React.createElement("div", {
                      className: tagsWrapper
                    }, notTagsMsg, renderTags)));
}

function getStaticProps(_ctx) {
  var tagsDictionary = Mdx__helpers$RescriptMonorepo.createTagsDictionary("blog");
  var props = {
    tags: tagsDictionary
  };
  return Promise.resolve({
              props: props
            });
}

export {
  $$default ,
  $$default as default,
  getStaticProps ,
  
}
/* pageWrapper Not a pure module */
