// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";
import * as Ion$RescriptMonorepo from "./components/icons/Ion.mjs";
import * as Utils$RescriptMonorepo from "./utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "./styles/tailwind/Tailwind.mjs";
import * as HeadConfiguration$RescriptMonorepo from "./layouts/HeadConfiguration.mjs";

var wrapper = Tailwind$RescriptMonorepo.merge([Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.gridCols("v2"),
            Tailwind$RescriptMonorepo.maxW("xl6"),
            Tailwind$RescriptMonorepo.mx("auto"),
            Tailwind$RescriptMonorepo.mt("v6"),
            Tailwind$RescriptMonorepo.grid
          ])]);

var hover = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.selector("&:hover", [
            Tailwind$RescriptMonorepo.srOnly,
            Tailwind$RescriptMonorepo.noSrOnly,
            Tailwind$RescriptMonorepo.bg(0.5, "blue700")
          ])]);

var alegreya = Tailwind$RescriptMonorepo.twStyle([[CssJs.fontFamily({
              NAME: "custom",
              VAL: "Alegreya Sans"
            })]]);

var crimson = Tailwind$RescriptMonorepo.twStyle([[CssJs.fontFamily({
              NAME: "custom",
              VAL: "Crimson Pro"
            })]]);

var jetBrains = Tailwind$RescriptMonorepo.twStyle([[CssJs.fontFamily({
              NAME: "custom",
              VAL: "JetBrains Mono"
            })]]);

var shadow = Tailwind$RescriptMonorepo.twStyle([Tailwind$RescriptMonorepo.shadow("xl")]);

function $$default(param) {
  return React.createElement(HeadConfiguration$RescriptMonorepo.make, {
              children: React.createElement("div", {
                    className: wrapper
                  }, React.createElement("div", undefined, React.createElement("h2", {
                            className: Tailwind$RescriptMonorepo.merge([hover])
                          }, Utils$RescriptMonorepo.str("Bs-TailwindCSS")), React.createElement("h2", {
                            className: Tailwind$RescriptMonorepo.merge([alegreya])
                          }, Utils$RescriptMonorepo.str("This is a level 2 heading")), React.createElement("h2", {
                            className: Tailwind$RescriptMonorepo.merge([crimson])
                          }, Utils$RescriptMonorepo.str("This is a level 2 heading")), React.createElement("h2", {
                            className: Tailwind$RescriptMonorepo.merge([jetBrains])
                          }, Utils$RescriptMonorepo.str("This is a level 2 heading")), React.createElement("input", {
                            className: Tailwind$RescriptMonorepo.merge([shadow]),
                            id: "",
                            name: "",
                            placeholder: "Put some text here",
                            type: "text"
                          }), React.createElement("button", undefined, React.createElement("svg", {
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", undefined, React.createElement("svg", {
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", undefined, React.createElement("svg", {
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", undefined, React.createElement("svg", {
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement(Ion$RescriptMonorepo.Outline.add, {
                            className: Tailwind$RescriptMonorepo.merge([Tailwind$RescriptMonorepo.twStyle([
                                        Tailwind$RescriptMonorepo.textColor(undefined, "red400"),
                                        Tailwind$RescriptMonorepo.fillCurrent
                                      ])])
                          }), React.createElement("div", undefined), React.createElement("div", undefined), React.createElement("p", undefined, Utils$RescriptMonorepo.str("Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias optio labore natus rem tempora veritatis. Praesentium quia, modi necessitatibus nulla adipisci, veniam itaque officiis rem voluptatem fugit cumque omnis nam nostrum natus tenetur voluptatibus placeat optio quasi, voluptatum obcaecati. Facere voluptatum veniam fugiat nihil dolorem eos quo nulla corrupti dicta.")), React.createElement("div", undefined, React.createElement("div", undefined, Utils$RescriptMonorepo.str("1")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("2")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("3")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("4")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("5")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("6")), React.createElement("div", undefined, Utils$RescriptMonorepo.str("7")))), React.createElement("div", undefined, React.createElement("h2", {
                            className: "text-5xl text-gray-800 text-opacity-80 mb-4 leading-none"
                          }, Utils$RescriptMonorepo.str("Normal TailwindCSS")), React.createElement("input", {
                            className: "placeholder-red-400 placeholder-opacity-90 ring-yellow-500 ring-4 mb-4",
                            id: "",
                            name: "",
                            placeholder: "Put some text here",
                            type: "text"
                          }), React.createElement("button", {
                            className: "block p-3 mb-4 bg-gray-600 text-white"
                          }, React.createElement("svg", {
                                className: "animate-spin h-5 w-5 text-white inline-block mr-3",
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", {
                            className: "block p-3 mb-4 bg-gray-600 text-white"
                          }, React.createElement("svg", {
                                className: "animate-bounce h-5 w-5 text-white inline-block mr-3",
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", {
                            className: "block p-3 mb-4 bg-gray-600 text-white"
                          }, React.createElement("svg", {
                                className: "animate-ping h-5 w-5 text-white inline-block mr-3",
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("button", {
                            className: "block p-3 mb-4 bg-gray-600 text-white"
                          }, React.createElement("svg", {
                                className: "animate-pulse h-5 w-5 text-white inline-block mr-3",
                                fill: "none",
                                viewBox: "0 0 24 24",
                                xmlns: "http://www.w3.org/2000/svg"
                              }, React.createElement("circle", {
                                    className: "opacity-25",
                                    cx: "12",
                                    cy: "12",
                                    r: "10",
                                    stroke: "currentColor",
                                    strokeWidth: "4"
                                  }), React.createElement("path", {
                                    className: "opacity-75",
                                    d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
                                    fill: "currentColor"
                                  })), Utils$RescriptMonorepo.str("Button")), React.createElement("div", {
                            className: "w-20 h-20 bg-indigo-600 mb-4"
                          }), React.createElement("div", {
                            className: "w-20 h-20 bg-indigo-600 rounded-r-full mb-4"
                          }), React.createElement("p", {
                            className: "text-red-800 text-opacity-85"
                          }, Utils$RescriptMonorepo.str(" Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus a, quidem, ducimus, molestiae officiis beatae veritatis voluptates expedita mollitia ad dicta pariatur. Iusto totam delectus modi nulla asperiores esse voluptatem nam doloremque aliquid, laborum id impedit ullam quod eligendi accusantium illum aperiam, ratione est ipsam soluta sed aliquam? Quam, magni.")), React.createElement("div", {
                            className: "grid grid-cols-3 gap-4"
                          }, React.createElement("div", {
                                className: "border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("1")), React.createElement("div", {
                                className: "border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("2")), React.createElement("div", {
                                className: "border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("3")), React.createElement("div", {
                                className: "col-span-2 border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("4")), React.createElement("div", {
                                className: "border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("5")), React.createElement("div", {
                                className: "border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("6")), React.createElement("div", {
                                className: "col-span-3 border border-red-400 border-dashed"
                              }, Utils$RescriptMonorepo.str("7")))))
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* wrapper Not a pure module */
