// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Tailwind$RescriptMonorepo from "../../styles/tailwind/Tailwind.mjs";

var elementStyles = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.m("v0"),
      Tailwind$RescriptMonorepo.py("v4"),
      Tailwind$RescriptMonorepo.pl("v6"),
      Tailwind$RescriptMonorepo.text("base"),
      Tailwind$RescriptMonorepo.breakWords,
      Tailwind$RescriptMonorepo.bg(undefined, "indigo100"),
      Tailwind$RescriptMonorepo.borderL(4),
      Tailwind$RescriptMonorepo.borderColor("indigo800"),
      Tailwind$RescriptMonorepo.italic,
      Tailwind$RescriptMonorepo.shadow("sm"),
      Tailwind$RescriptMonorepo.mb("v6")
    ]);

var Styles = {
  elementStyles: elementStyles
};

function Blockquote(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("blockquote", {
              className: Tailwind$RescriptMonorepo.merge([
                    elementStyles,
                    className
                  ])
            }, children);
}

var make = Blockquote;

export {
  Styles ,
  make ,
  
}
/* elementStyles Not a pure module */
