// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LiMdx(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, children);
}

var make = LiMdx;

export {
  make ,
  
}
/* react Not a pure module */
