// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";
import * as Tailwind$RescriptMonorepo from "../../styles/tailwind/Tailwind.mjs";
import * as LiMdxOrdered$RescriptMonorepo from "./LiMdxOrdered.mjs";

var elementStyles = Tailwind$RescriptMonorepo.merge([Tailwind$RescriptMonorepo.style(Tailwind$RescriptMonorepo.tw([Tailwind$RescriptMonorepo.mb("v6")]))]);

var Styles = {
  elementStyles: elementStyles
};

function OlMdx(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("ol", {
              className: CssJs.merge([
                    elementStyles,
                    className
                  ])
            }, React.Children.map(children, (function (child, index) {
                    return React.createElement(LiMdxOrdered$RescriptMonorepo.make, {
                                children: child,
                                order: index + 1 | 0
                              });
                  })));
}

var make = OlMdx;

export {
  Styles ,
  make ,
  
}
/* elementStyles Not a pure module */
