// Generated by ReScript, PLEASE EDIT WITH CARE


var Screens;

var Spacing;

var SpacingNegative;

var Proportions;

var ProportionsNegative;

var Opacity;

var BorderRadius;

var BorderWidth;

var BoxShadow;

var MaxWidth;

var ZIndex;

var Order;

var Duration;

var TimingFunction;

var KeyFrames;

var Skew;

var Scale;

var Rotate;

var Colors;

var FontSize;

var LetterSpacing;

var LineHeight;

var FontWeight;

var GridCols;

var ColSpan;

var ColStart;

var GridRows;

var RowSpan;

var Row;

export {
  Screens ,
  Spacing ,
  SpacingNegative ,
  Proportions ,
  ProportionsNegative ,
  Opacity ,
  BorderRadius ,
  BorderWidth ,
  BoxShadow ,
  MaxWidth ,
  ZIndex ,
  Order ,
  Duration ,
  TimingFunction ,
  KeyFrames ,
  Skew ,
  Scale ,
  Rotate ,
  Colors ,
  FontSize ,
  LetterSpacing ,
  LineHeight ,
  FontWeight ,
  GridCols ,
  ColSpan ,
  ColStart ,
  GridRows ,
  RowSpan ,
  Row ,
  
}
/* No side effect */
