// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";
import * as Utils$RescriptMonorepo from "../utils/Utils.mjs";
import * as Tailwind$RescriptMonorepo from "../styles/tailwind/Tailwind.mjs";

var globalStyles = Tailwind$RescriptMonorepo.merge([Tailwind$RescriptMonorepo.twStyle([
            Tailwind$RescriptMonorepo.fontFamilies([{
                    NAME: "custom",
                    VAL: "Nunito Sans"
                  }]),
            Tailwind$RescriptMonorepo.w("full"),
            Tailwind$RescriptMonorepo.h("full"),
            Tailwind$RescriptMonorepo.mx("auto"),
            Tailwind$RescriptMonorepo.overflowAuto,
            Tailwind$RescriptMonorepo.bg(undefined, "gray50"),
            Tailwind$RescriptMonorepo.textColor(undefined, "coolGray800"),
            Tailwind$RescriptMonorepo.fontSans
          ])]);

var container = Tailwind$RescriptMonorepo.twStyle([
      Tailwind$RescriptMonorepo.maxW("xl4"),
      Tailwind$RescriptMonorepo.mx("auto")
    ]);

var Styles = {
  globalStyles: globalStyles,
  container: container
};

function BsTailwindLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: globalStyles
            }, React.createElement(Head, {
                  children: null
                }, React.createElement("media", {
                      content: "width=device-width, initial-sacle=1.0",
                      name: "viewport"
                    }), React.createElement("title", undefined, Utils$RescriptMonorepo.str("Bs-TailwindCSS")), React.createElement("link", {
                      href: "https://fonts.gstatic.com",
                      rel: "preconnect"
                    }), React.createElement("link", {
                      href: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700;900&display=swap",
                      rel: "stylesheet"
                    })), React.createElement("div", {
                  className: container
                }, children));
}

var make = BsTailwindLayout;

export {
  Styles ,
  make ,
  
}
/* globalStyles Not a pure module */
